### ISSUE TITLE
Incorrect example curl commands

### ISSUE THREAD

**Issue by chlam1** [jfrog/artifactory-user-plugins#120]
Using this curl command taken from the README:

curl -X POST -v -u admin:password "http://localhost:8080/artifactory/api/plugins/execute/cleanup?params=months=1;repos=libs-release-local;dryRun;paceTimeMS=2000"

Results in the following being executed (from artifactory.log):

2017-08-07 12:50:00,562 [http-nio-8081-exec-9] [INFO ] (artifactCleanup     :-2) - Starting artifact cleanup for repositories null, until 6 months ago with pacing interval 0 ms dryrun: false

Also, the example curl command given in artifactCleanup.groovy is different from the README:

curl -i -uadmin:password -X POST "http://localhost:8081/artifactory/api/plugins/execute/cleanup?params=months=1|repos=libs-release-local|dryRun=true|paceTimeMS=2000"

Most notably it contains pipes instead of semi-colons.

**Comment by elioengcomp** [comment]
@chlam1 the pipe version is for Artifactory 4.x or older. The semi-colons version works on Artifactory 5.x.

**Comment by DarthFennec** [comment]
As described in the [release notes](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory5.0), the version of Tomcat used by Artifactory >= 5.x does not support pipes in urls. Support for semicolons was added in 5.0 to work around this. We are in the process of converting all the documentation here to provide examples in both formats, but we appear to have missed this example, so thank you for pointing it out.

**Comment by chlam1** [comment]
@elioengcomp Thanks, we're running version 4.2.1 so we'll use the pipes.

@DarthFennec Please also note that the parameter "dryRun" has no value in the README example.

**Comment by axel3rd** [comment]
Fixed in #122 (dedicated commit)
