### ISSUE TITLE
artifactoryCleanup cleaning part of a docker image within a docker repository  

### ISSUE THREAD

**Issue by meedel** [jfrog/artifactory-user-plugins#143]
Cleaning a docker image in a docker repository leaves a "broken" image. Not all of the image is being cleaned. There are sha256_xxx files left in the image directory. I did a cleaning with the option over 12 months but some sha256 files remained even if the artifact was older.

**Comment by DarthFennec** [comment]
Apologies for the complete silence here for so long, I just discovered this issue while scrolling through. I don't expect you're waiting on an answer anymore, but just in case, the current recommendation is to use [cleanDockerImages](https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup/cleanDockerImages).
