### ISSUE TITLE
conda plugin should create a noarch directory

### ISSUE THREAD

**Issue by beenje** [jfrog/artifactory-user-plugins#161]
I installed the conda user plugin.
I successfully deployed a conda package. I now have a linux-64 and osx-64 directory under the repository.
When I run a command with the artifactory channel, I get the following warning:
```
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://artifactory.xxx.xxx:443/artifactory/ics-conda

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.........
```

I tried creating manually the noarch directory and the repodata.json files but that resulted in the conda plugin to throw an exception. Full trace here:
https://gist.github.com/beenje/ac5342e9730f2bc7f386575978519542

I guess to avoid the warning I have to upload a noarch package. But it would be nice if the conda plugin would handle that itself.
Or am I missing something?

**Comment by elioengcomp** [comment]
@beenje Can you share the content of the repodata.json file you are trying to uploade under noarch folder?

I was able to do that and got no errors from conda plugin using the following content:

```json
{
    "info": {},
    "packages": {}
}
```

**Comment by beenje** [comment]
As mentioned in the warning, I tried to upload an empty object:
`{}`

I uploaded a noarch package and then deleted it and my repodata.json is now identical to yours:
```
{
    "info": {},
    "packages": {}
}
```

That's indeed what should be used. It would be nice if the plugin was initializing that automatically.

**Comment by elioengcomp** [comment]
@beenje can you confirm that the warning message is gone after uploading the repodata.json file with the changed content?

**Comment by beenje** [comment]
Yes, no more warning from conda commands with this repodata.json under noarch.

**Comment by beenje** [comment]
conda support has been officially added to artifactory from version 6.3: https://www.jfrog.com/confluence/display/RTF/Conda+Repositories
This issue can be closed.
