### ISSUE TITLE
artifactoryCleanup stops working on SSL only Artifactory

### ISSUE THREAD

**Issue by lachnerd** [jfrog/artifactory-user-plugins#163]
Hi,
we moved to a new artifactory instance that is accessible ssl only and i wanted to use artifactoryCleanup Script as usual. Unfortonately it stopped working.

i get an 301 Moved permanently:

*   Trying <IP>...
* Connected to <URL> (<IP>) port 80 (#0)
* Server auth using Basic with user 'admin'
> POST /artifactory/api/plugins/execute/cleanup?params=months=1|repos=repo-snapshot-local||paceTimeMS=500 HTTP/1.1
> Host: <HOST-URL>
> Authorization: Basic APIKEY
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 11 Oct 2017 12:13:07 GMT
< Server: Apache
< Location: https://<URL>:443/artifactory/api/plugins/execute/cleanup?params=months=1|repos=repo-snapshot-local||paceTimeMS=500
< Content-Length: 334
< Content-Type: text/html; charset=iso-8859-1

I also tried that deleteEmptyFolders Plugin - it works like expected. What is special about cleanup plugin?

**Comment by markgalpin** [comment]
If you did this with curl, use -L on the curl command and it should work fine.  Also should work if you use https in the URL originally?  90% sure this is not the user plugin, but instead has to do with your reverse proxy config.

**Comment by lachnerd** [comment]
thanks I will try that

**Comment by lachnerd** [comment]
I know the reason now.
It had nothing to do with SSL or the reverse proxy config.
Syntax changed from Artifactroy 4.x to 5.x:

>  Artifactory 5.x curl -X POST -v -u admin:password "http://localhost:8080/artifactory/api/plugins/execute/cleanupCtl params=command=adjustPaceTimeMS;value=-1000"

deleteemptydirs plugins si working because it only has 1 param - thats all
