### ISSUE TITLE
createCopy plugin does not copy docker image properties 

### ISSUE THREAD

**Issue by stmosher27** [jfrog/artifactory-user-plugins#165]
https://www.jfrog.com/jira/projects/RTFACT/issues/RTFACT-15098

if you run the createCopy plugin between two local repositories and upload a docker image to the source. When the image is copied over to the target repo, the docker image properties Artifactory assigns the image are gone resulting in the docker info tab being blank and not being able to pull the image from the copy repo.

If you enter the 4 properties manually, all is well

**Comment by avivbl** [comment]
_uploads folder of the target repository remains full and Docker info does not get generated.

**Comment by korjek** [comment]
any updates here?

**Comment by bhanurp** [comment]
Due to inactivity over the past few years, we are closing this issue to keep the repository organized.
If it is still relevant please feel free to reopen or create a new issue with updated details.
