### ISSUE TITLE
archiveOldArtifacts  Get error messages. result: the artifact is gone!

### ISSUE THREAD

**Issue by meedel** [jfrog/artifactory-user-plugins#185]
When testing this user plugin, I get errors with the result that the artifact is gone.

I try to do: curl -X POST -v -u admin:xxxxxxxxx "http://xx.xx.xx.xx:0000/artifactory/api/plugins/execute/archive_old_artifacts?params=srcRepo=mvn-legacy-local%7CarchiveRepo=archive-local%7CfilePattern=*.war%7CageDays=100"

I get the following ERROR messages:
2018-01-11 09:26:40,388 [http-nio-8081-exec-7] [WARN ] (archiveOldArtifacts :258) - About to archive artifact: mvn-legacy-local:Nl/kadaster/brkbag/monitor/appl/monitor-application-web/1.0.1.14/monitor-application-web-1.0.1.14.war
2018-01-11 09:26:40,392 [http-nio-8081-exec-7] [INFO ] (o.a.e.UploadServiceImpl:512) - Deploy to 'mvn-legacy-local:Nl/kadaster/brkbag/monitor/appl/monitor-application-web/1.0.1.14/monitor-application-web-1.0.1.14.war' Content-Length: unspecified
2018-01-11 09:26:40,401 [http-nio-8081-exec-7] [ERROR] (archiveOldArtifacts :268) - Call to deploy artifact mvn-legacy-local:Nl/kadaster/brkbag/monitor/appl/monitor-application-web/1.0.1.14/monitor-application-web-1.0.1.14.war failed!
2018-01-11 09:26:40,418 [http-nio-8081-exec-7] [ERROR] (archiveOldArtifacts :309) - Call to move artifact mvn-legacy-local:Nl/kadaster/brkbag/monitor/appl/monitor-application-web/1.0.1.14/monitor-application-web-1.0.1.14.war failed!

Result: There is only one entry in the archive-local repo of the 1-byte large war file. In the srcRepo there is no reference anymore and the 'displaced' war file has completely disappeared.
And I can't get any info anymore from the 'moved' war file through the storage api call.

The original information of the artefact is:

  "repo" : "mvn-legacy-local",
  "path" : "/Nl/kadaster/brkbag/monitor/appl/monitor-application-web/1.0.1.14/monitor-application-web-1.0.1.14.war",
  "created" : "2016-01-17T05:06:26.728+01:00",
  "createdBy" : "anonymous",
  "lastModified" : "2015-10-13T12:20:08.000+02:00",
  "modifiedBy" : "anonymous",
  "lastUpdated" : "2016-01-17T05:06:26.733+01:00",
  "mimeType" : "application/java-archive",
  "size" : "22005826",
  "checksums" : {
    "sha1" : "83f34a46b112175ba079090fb379048f84563e84",
    "md5" : "de9bb0a0fac32c5b6de2fb1a8c56c620"
  },
  "originalChecksums" : {
    "sha1" : "83f34a46b112175ba079090fb379048f84563e84",
    "md5" : "de9bb0a0fac32c5b6de2fb1a8c56c620"
  },
  "uri" : "http://ota-portal.so.kadaster.nl/artifactory/api/storage/mvn-legacy-local/nl/kadaster/brkbag/monitor/appl/monitor-application-web/1.0.1.14/monitor-application-web-1.0.1.14.war"

Please advice

**Comment by DarthFennec** [comment]
It looks like those errors are being printed in ... well, in error. The plugin is behaving as expected, though.

As far as I can tell, the purpose of this plugin is to preserve the file structure and properties of old build artifacts, while also conserving disk space by deleting them. So your war file will be replaced with a one-byte stub file with the same path, name, and properties, and then it will be moved to the archive repository. If this isn't the behavior you were looking for, you could let me know what your use case is, and I'll be happy to try and help you find the right approach.

In the meantime, I've fixed the bug that causes those error messages to print, and I've updated the readme file to hopefully be a little more clear about what the plugin actually does. Thanks for reaching out!

**Comment by meedel** [comment]
Hello DarthFennec,
As I read it, a dummy entry of the artifact was placed in the srcRepo and the artifact itself moved to the archiveRepo. What I see now is that a dummy entry is placed in the archiveRepo and the artifact itself is removed. Is that the correct way you mentioned?

**Comment by DarthFennec** [comment]
Yes, the dummy is placed in the archive repo and the artifact is removed. The first time I read it, I thought it was the other way too ... I think the readme just wasn't too clear.
