### ISSUE TITLE
Build Replication with particualr build number or for a particular repository

### ISSUE THREAD

**Issue by ECIDSupport** [jfrog/artifactory-user-plugins#198]
The buildReplication plugin will replicate every build that does not exists in the target Artifactory instance. But we want to replicate only some builds where the upload is to a particular repository.
buildReplication plugin does not handle this scenario.

**Comment by elioengcomp** [comment]
@ECIDSupport you should use the [buildSync](https://github.com/JFrogDev/artifactory-user-plugins/tree/master/build/buildSync) plugin instead. With that plugin you can define replication rules just for the builds you want to replicate.
