### ISSUE TITLE
Support for terraform registry

### ISSUE THREAD

**Issue by turip** [jfrog/artifactory-user-plugins#210]
Given that I have no write access to your jira boards I would create a ticket here regarding: https://www.jfrog.com/jira/browse/RTFACT-16117

I did a quick hack to have support for terraform registry in artifactory as an user plugin. See the details here:
https://github.com/turip/artifactory-terraform-module-registry

I wonder if it is possible to include that code into this repository (I can create the PR if needed) or at least I would love if you can update the ticket with this temporary implementation until the official one comes.

**Comment by jfrog-aparicio** [comment]
Hello Peter,

Wow, it looks like it has been quite a long time since you posted this. If your solution still works, feel free to add a comment to the JIRA. I will send you details on creating an account.
