### ISSUE TITLE
ArtifactoryCleanup Plugin repos var read as null

### ISSUE THREAD

**Issue by leonallen22** [jfrog/artifactory-user-plugins#217]
artifactoryCleanup.groovy plugin did not work as expected

Command run:
`curl -v -H "X-JFrog-Art-Api:<API-Key>" -X POST http://artifactory.adtran.com:8081/artifactory/api/plugins/execute/cleanup?params=seconds=1;repos=example-repo`

`# Artifactory.log
<timestamp> [http-nio-8081-exec-8] [INFO ] (artifactCleanup     :-2) - Starting artifact cleanup for repositories null, until 1 seconds ago with pacing interval 0 ms, dryrun: false, disablePropertiesSupport: false`

**Comment by elioengcomp** [comment]
Hi @leonallen22 ,

Which Artifactory version are you using? 

It looks like the plugin is not being able to read the repos parameter. Have you tried using `|` or escaping the `;` with `%3B`

**Comment by leonallen22** [comment]
Artifactory Enterprise 5.10.3 rev 51003900
Have not tried that. It does look like '|' should be used for this version. I see that in the groovy file, but should that be made clear in the README?

**Comment by DarthFennec** [comment]
It should. It's made clear in other plugins' READMEs, and in this README the last example gives both versions. But the other examples should as well.

**Comment by leonallen22** [comment]
Well, looking at that example, the "For Artifactory 5.x" example uses ';'
Also the groovy file says "Prior Artifactory 5.x, use pipe '|' and not semi-colons ';'" (line 32)

Assuming that it means "Prior to Artifactory 5.x", the ambiguous wording should be fixed as well

**Comment by elioengcomp** [comment]
Pull request created:
https://github.com/JFrogDev/artifactory-user-plugins/pull/218

**Comment by DarthFennec** [comment]
Perfect, merged.
