### ISSUE TITLE
Can't install conda package x264-1!152.20180717-h470a237_0.tar.bz2 from artifactory remote repository

### ISSUE THREAD

**Issue by beenje** [jfrog/artifactory-user-plugins#226]
I'm not sure if this is an Artifactory or conda plugin issue.

I've created a conda-forge remote repository on artifactory that points to https://conda.anaconda.org/conda-forge

In my .condarc I have:
```
channel_alias: https://artifactory.xxxx.xx.xx/artifactory
channels:
  - conda-forge
```

It usually works fine, but I can't install the latest version of the x264 package:

```
$ conda create -n foo x264
Solving environment: done

## Package Plan ##

  environment location: /Users/xxxxxxxxxxx/miniconda3/envs/foo

  added / updated specs:
    - x264


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    x264-1!152.20180717        |       h470a237_0         2.4 MB  conda-forge

The following NEW packages will be INSTALLED:

    x264: 1!152.20180717-h470a237_0 conda-forge

Proceed ([y]/n)?


Downloading and Extracting Packages
x264-1!152.20180717  |  2.4 MB |                                                                                                                                                                     |   0%

CondaHTTPError: HTTP 404 NOT FOUND for url <https://artifactory.xxxx.xx.xx/artifactory/conda-forge/osx-64/x264-1!152.20180717-h470a237_0.tar.bz2>
Elapsed: 00:00.024469

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

I guess that artifactory doesn't like the "!" in the version of the package...

**Comment by elioengcomp** [comment]
Hi @beenje 

The `!` character in the path is reserved by Artifactory to download archive entries (See: https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ArchiveEntryDownload)

That is way you are getting a 404 error for that request. Artifactory is trying to serve an entry named `152.20180717-h470a237_0.tar.bz2` from an archive at `/conda-forge/osx-64/x264-1` and is not able to find this file.

Best.
Elio

**Comment by beenje** [comment]
Thanks for the quick answer @elioengcomp!
The fact that `!` is an Artifactory reserved character is quite annoying.
It's a valid character according to [Python PEP 440](https://www.python.org/dev/peps/pep-0440/#version-scheme) which conda acknowledges:
```
The canonical public version identifiers MUST comply with the following scheme:

[N!]N(.N)*[{a|b|rc}N][.postN][.devN]

- Epoch segment: N!
```

This issue could arise with Python packages as well.
Should I open an issue on https://www.jfrog.com/jira/projects/RTFACT?

**Comment by elioengcomp** [comment]
@beenje , It is a good idea to open an issue to the Artifactory team. They might introduce a feature to disable the download archive entry API or maybe a way to configure which character to use to separate the archive name from the archive entry, instead of the default `!`

**Comment by beenje** [comment]
I created an issue on jira: https://www.jfrog.com/jira/browse/RTFACT-17199
This ticket can be closed. Thanks!
