### ISSUE TITLE
Artifactory Cleanup

### ISSUE THREAD

**Issue by vigneshrs** [jfrog/artifactory-user-plugins#23]
From the below link we got an groovy script for artifactory clean up process.

https://github.com/JFrogDev/artifactory-user-plugins/blob/master/cleanup/artifactCleanup.groovy

But the above script takes "repos" input as a array string & not accepting \* values. 

So that if we try to fetch artifacts like "/libs-releases-local/com/testrepo*" it says not found. But there is the paths available as below.

/libs-releases-local/com/testrepo1
/libs-releases-local/com/testrepo2
/libs-releases-local/com/testrepo3

**Comment by trisquel87** [comment]
@vigneshrs  I'm checking the code of this script and doesn't have support for regular expressions:
[](https://github.com/JFrogDev/artifactory-user-plugins/blob/master/cleanup/artifactCleanup/artifactCleanup.groovy)

Your issue has more than 2 years, I can implement this funcionality if you are still interesting.

**Comment by Imranonline** [comment]
Hi Thanks for the plugin, How to run the job every 5 mins

**Comment by elioengcomp** [comment]
@Imranonline we need to use a cron expression to setup this plugin. 

To run any of your policies every 5 minutes use the following cron expression to setup it at `artifactCleanup.properties` file:

```
0 0/5 * * * ? 
```

We can get more information on cron expressions [here](http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger).

**Comment by hamstermaster** [comment]
@elioengcomp - quick question about properties file - when I change something in it, how to apply my change in Artifactory? I assume I should reload plugin, but plugin code is not changed so I cannot reload it without Artifactory restart?

**Comment by elioengcomp** [comment]
@hamstermaster you can `touch` the plugin file to change the lastUpdated timestamp and call the reload plugins API.
