### ISSUE TITLE
The new ArtifactoryCleanup Plugin doesn't create log entries in artifactory.log 

### ISSUE THREAD

**Issue by jiangx2018** [jfrog/artifactory-user-plugins#230]
when use the old version of ArtifactoryCleanup Plugin,  it generated logs in artifactory.log as below:

2018-08-14 08:08:05,898 [http-nio-8081-exec-523] [INFO ] (artifactCleanup     :-2) - Starting artifact cleanup for repositories [libs-ecn-local], until 6 months ago with pacing interval 2000 ms dryrun: true

After updated to the latest ArtifactoryCleanup Plugin version,  there is no any entry in artifactory.log when run the same command like below:
curl -X POST -v -u jiangx "https://artifactory.cboe.com/artifactory/api/plugins/execute/cleanup?params=timeUnit=month;timeInterval=1;repos=libs-ecn-local;dryRun=true;paceTimeMS=2000;disablePropertiesSupport=true"

only found one entry in request.log:
20180814083535|87|REQUEST|10.137.228.252|jiangx|POST|/api/plugins/execute/cleanup|HTTP/1.1|200|-1

Any idea why?   Thanks.

**Comment by elioengcomp** [comment]
Hi @jiangx2018 

I can see the log command in the plugin source code [on line 155](https://github.com/jfrog/artifactory-user-plugins/blob/master/cleanup/artifactCleanup/artifactCleanup.groovy#L155)

Can you confirm you have the plugin logs set to the right verbosity in your `logback.xml` file? It should look like the snippet below (pay attention to the logger name, It has to match the plugin groovy file name):

```
<logger name="artifactCleanup">
     <level value="info"/>
</logger>
```

**Comment by jiangx2018** [comment]
Hi, Elio:
                Thanks lot for your reply.
                Yes I did have the plugin logs set in logback.xml (it’s working for the old ArtifactoryCleanup Plugin).   See below:

# more logback.xml

...skipping

    <logger name="artifactCleanup">
        <level value="info" />
    </logger>

BTW, the old and new plugin groovy file names are same:

# ls -l artifactCleanup.groovy*
-rw-r--r-- 1 artifactory artifactory 13728 Aug 10 15:26 artifactCleanup.groovy                                        --> new
-rw-rw-r-- 1 artifactory artifactory  5519 Jan 26  2018 artifactCleanup.groovy.0810                              --> saved old one


jiangx@2018

**Comment by jiangx2018** [comment]
The issue was resolved by restart Artifactory. the artifactory.log has all info logged after that.  Thanks.
