### ISSUE TITLE
Congestion Control / DoS-Guard

### ISSUE THREAD

**Issue by AlexanderDenk-EE** [jfrog/artifactory-user-plugins#233]
Hi there,

first a want to thank you for the great and fast feedback on my last two issues. We got the improvements into our live system and they are really performing well.

Today I got a new problem I would like to talk about and to share some toughs and opinions on. As far as I know Artifactory does not have a build-in mechanism to avoid congestion.

**Let's imagine the following fictional scenario:**
For some reason a CI cluster building resource intensive projects decides to use Artifactory as Docker image source directly instead of the build in caches. As there are many jobs running in parallel and as the images have multiple gigabytes a huge amount of data is requested at once. 

**What happens:**
The massive download requests of a single project bring down the download performance of the whole Artifactory instance and may cause various problems. 

**What's the problem:**
A single project can accidentally lead to a denial of service for other projects.

**Counter Measures:**
There are several levels counter measures can be placed at and there are multiple ways to handle such issues, for example the traffic can be routed to multiple Artifactories to avoid a single serve to be affected that much. However, I'm not happy with the situation that there is no last line of defense in Artifactory itself. If multiple protection mechanisms fail, there is no layer in Artifactory that stops the disaster.

**Basis for Discussion:**
I'm not sure if this should be a feature request for the core functionality of Artifactory or a propose for a plug-in. Also far away from being trivial to build a good congestion control mechanism and the public Artifactory-API may even be to restrictive to build complex mechanisms. However, I think it should be possible to build a plug-in that can be a simple and effective guide to avoid a disaster. This may not be the perfect solution, but it should be better than nothing.

**Ideas:**
- A simple approach could be, that a project can define a property that defines the maximum number of parallel connections for an artifact/repository. If more requests are coming in they can be canceled (I think there is no possibility to queue them). Also I would roll out the restriction only for bigger files, I don't mind if there are downloaded 100 1MB files at once, but I do mind if there are downloaded 100 120 GB Docker images at once.  
- I think the maximum connections value can be set static and also can be quite high, because the main goal is not to be absolutely fair or to provide the best quality of service, it's more about to avoid complete disasters and donwtimes until a issue is detected and fixed.
- The monitoring could be done with download start/end handlers.
- This could also be done on configuration-file basis.

I would be glad if I get some feedback and thoughts on this. Every input is welcome :)
The idea above is just a first sketch that has been on my mind, so there may be better and more effective solutions.

**Comment by elioengcomp** [comment]
Hi @AlexanderDenk-EE,

Thank you for your message.

Although a user plugin to control the maximum number of concurrent connections is technically doable, we don't believe that it is required to achieve what you want. We believe that you should have resources available accordingly to your load, but if you are looking for a way to throttle the incoming request, you can use Tomcat's maxThreads and maxConnections to do that.

Please see this post about how to tune your Artifactory instance for heavy loads: https://jfrog.com/knowledge-base/how-do-i-tune-artifactory-for-heavy-loads/

**Comment by AlexanderDenk-EE** [comment]
Hi, thanks for your response.

Basically I agree with you, but as I said the target is not to limit the connections in general or to handle heavy loads in general (I'm currently working on this topic for future use cases as well :)).
It's more about what happens when the user of a single repository get's weird for some reason. That may cause accidental DoS attacks on the whole system caused by a single project/repository consumer. The load that can be caused is multiple times of the normal peek load the system must be able to handle. Also the server's are not the problem, the real problem is the network bandwidth that cannot be upgraded that simple. Limiting the connections and the threads helps to avoid more systems will be affected, but it won't help other projects that are lying within the same Artifactory HA.

My primary goal would be to limit the impacts of a project that has gone mad to the repositories used by this project.

For example if `CI A` is a consumer of repository `X` and decides to start a DoS attack on repository `X` (maybe the caching mechanism does not work any more) i wand to start rejecting the requests on repository `X` that are coming from `CI A` (because it has already `n` large downloads running in parallel), but I do not want to limit `CI B` that consumes moderate data of repository `Y` and repository `Z`. 

I hope that helps :)

**Comment by elioengcomp** [comment]
@AlexanderDenk-EE has this scenario where your CI cause an accidental DoS to your Artifactory instance ever happened to you? 

It looks like it could be avoided by configurations on the CI side, like controlling the max number of concurrent builds that can run in parallel for jobs that share repositories in Artifactory and queueing new builds when you reach that number.

**Comment by markgalpin** [comment]
@AlexanderDenk-EE so how much of what you want can be done at the NGINX/LB layer?  For example on [the NGINX blog](https://www.nginx.com/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus/) we see that there's a mechanism to limit the number of connections from a single IP address.  What you're suggesting could possibly be managed with an altResponse plugin that assessed state of how many users were requesting from a single repository and killed it,  though we only have access to headers, I'd have to double-check if that includes the source IP (although we definitely have the source user) but user plugins that share state across multiple events have a number of complexities that I prefer to avoid...  
It might be best to open a support ticket for this and request a session?

**Comment by AlexanderDenk-EE** [comment]
@elioengcomp:
Yes, the scenario is from a real world example that happend already two times. For the CI everything looked fine, because the system is basically capable of handling a really high number of concurrent builds (and also must be able to to do so...). The problem in our cases was that local caches didn't work as intended. For the CI this is hard to detect in general. Moreover it does no relay on the number of connections if this behavior causes trouble, it relays also on the size of the files that are downloaded. 

@markgalpin 
Thanks for your input. Sadly NGINX would not help very much because the traffic is caused by multiple IP addresses. Also a single IP address might be used by different projects. The application that has the most semantic information available to detect such problems is Artifactory, because it knows the size of the files and the users that are involved in parallel. 
I'm also not very happy to place such a feature that's monitoring the whole system state in a plug-in, but I'm also not sure if this should be a core functionality of Artifactory. On the other hand I think Artifactory should be able to deal with such scenarios at least in some way without relaying only on protection mechanisms of other systems.
The fact that people already managed twice to build such bugs in their pipelines, that wouldn't have been detected generically on another layer without causing collateral damage, showed us that there is at least some basic need to improve the situation. Also the expertise of Google showed us that engineers can be very good and pretty creative at bringing down systems accidentally :) A full featured load shedding would be great to avoid that, but I think a basic disaster prevention that's limiting the damage to the user that caused the issue would be a great start.

**Comment by markgalpin** [comment]
@AlexanderDenk-EE So, we use github issues for bug reports and minor feature requests, but if we're going to work on a plug-in like this (And I am not, at this time committing to do so), or in general any new plug-in or major artifactory feature, we will need you to file a support ticket and/or have your account representative set up a session.  Say you spoke to me on GitHub, and I'll be happy to handle the session personally.
