### ISSUE TITLE
Artifactory LDAP group is not refreshing itself to update with group members

### ISSUE THREAD

**Issue by rapture21** [jfrog/artifactory-user-plugins#237]
Artifactory LDAP group is not refreshing itself to update with group members, if a user is removed from a group at ldap server, he still holds group access until he login and logoff at artifactory to get it refreshed. or manually remove the user.

**consider a scenario:**

- I have a LDAP group1, which is configured under artifactory,
   group1 has user1 and user2

- at Artifactory, LDAP group1 is assigned as Admin access.
   both user1 and user2 login fine into artifactory and can see Admin access.

- user1 is moved out of team, so we decide to move the user1 out of LDAP group1.

- after some days we noticed, artifactory LDAP group1 still shows user1 intact.

- when user1 logins into artifactory he could see Admin access, even though he was removed from LDAP group1 from our LDAP server side, but access is still available on artifactory side, then user logsoff.

- again user1 tries to login, only then his access related to LDAP group1 vanishes

could anyone help me in fixing this security issue.
I have followed this info - https://jfrog.com/knowledge-base/when-do-the-groups-associated-with-an-ldap-user-get-updated-in-artifactory/ 
tried changing the "artifactory.security.authentication.cache.idleTimeSecs" but it did not help.

**Comment by elioengcomp** [comment]
@rapture21 this area is to discuss issues related to Artifactory User Plugins. Since your issue does not seem to be related to any user plugin, I'm closing this issue and I recommend you to open a support ticket so our support team can help you on your LDAP configuration.
