### ISSUE TITLE
Failed loading: deleteEmptyDirs.groovy

### ISSUE THREAD

**Issue by lksgithub** [jfrog/artifactory-user-plugins#238]
I followed the guideline in this [jfrog reference link](https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-DeployingPlugins), and put the groovy script (deleteEmptyDirs.groovy) under ${ARTIFACTORY_HOME}/etc/plugins. And then I submit the below REST api curl command according to the [jfrog rest api document](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ReloadPlugins). But it showed failure to upload. Please see the command and output below:
```
[root@scmdms01 plugins]# curl -u <admin_ac>:<admin_pw> -X POST https://mycompany/artifactory/api/plugins/reload
Successfully loaded:
Failed loading: deleteEmptyDirs.groovy
```
Any idea why it failed to install the plugin? Thank in advance!

**Comment by DarthFennec** [comment]
Try opening the file and make sure its contents are what you expect. Sometimes people accidentally download the HTML page instead of the Groovy file, which can cause loading to fail like this. You could also check the artifactory log to see if it has any further information on why the load failed.

**Comment by lksgithub** [comment]
I reloaded again and checked the log, it seems like the cron time is invalid. Please also see the snippet the error message below:
```
2018-09-05 10:12:55,770 [http-nio-8081-exec-4] [ERROR] (o.a.a.p.GroovyRunnerImpl:300) - Error loadin
g script from '/var/opt/jfrog/artifactory/etc/plugins/deleteEmptyDirs.groovy'.
groovy.lang.MissingMethodException: No signature of method: groovy.lang.Reference.scheduledDeleteEmp
tyDirs_0 0 * * * * () is applicable for argument types: (java.util.LinkedHashMap, deleteEmptyDirs$_r
un_closure2$_closure6$_closure7) values: [[cron:0 0 * * * * , delegate:org.artifactory.addon.plugin.
ScriptDelegate@5090305d, ...], ...]

This is the cron format I followed

* * * * * *
| | | | | | 
| | | | | +-- Year              (range: 1900-3000)
| | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
| | | +------ Month of the Year (range: 1-12)
| | +-------- Day of the Month  (range: 1-31)
| +---------- Hour              (range: 0-23)
+------------ Minute            (range: 0-59)
```

I wanted to set it to run at 00:00 every day, so I set it to be "0 0 * * * *"

**Comment by DarthFennec** [comment]
Artifactory doesn't actually use the standard cron format. Instead it uses the [Quartz library's format](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html) for cron expressions. So your expression should be:

```
0 0 0 * * ?
```

**Comment by lksgithub** [comment]
Thx for the reference! It WORKS now~

**Comment by DarthFennec** [comment]
Awesome! Glad I could help.
