### ISSUE TITLE
Json parsing error when execute "def json = new JsonSlurper().parse(new InputStreamReader(body.inputStream))"

### ISSUE THREAD

**Issue by wdquan1985** [jfrog/artifactory-user-plugins#240]
This is my execution user plugin.
`executions {
    serviceParameters { params, ResourceStreamHandle body ->
    assert body
    def json = new JsonSlurper().parse(new InputStreamReader(body.inputStream))
}`

When invoke the this plugin
-bash-4.2$ curl -X POST -v -u admin:password "http://10.243.82.228:8084/artifactory/api/plugins/execute/serviceParameters?params=~~~~~~~~"

There are the following error:
{
  "errors" : [ {
    "status" : 500,
    "message" : "Unable to determine the current character, it is not a string, number, array, or object\n\nThe current character read is '\u0000' with an int value of 0\nUnable to determine the current character, it is not a string, number, array, or object\nline number 1\nindex number 255\n\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\n...............................................................................................................................................................................................................................................................^"
  } ]
* Closing connection 0

**Comment by elioengcomp** [comment]
Hi @wdquan1985,

You are sending a POST request but I can't see the data payload you are trying to use from your curl command. It looks your user plugin is trying to read a JSON payload but you are not sending it. 

Can you confirm you are sending the payload as part of the request? 

Using curl it should look like this:

```
curl -d '{"key1":"value1", "key2":"value2"}' -X POST <YOUR_URL>
```
or

```
curl -d "@data.json" -X POST <YOUR_URL>
```

**Comment by wdquan1985** [comment]
@elioengcomp  Thanks, this issue is because I have not sent payload in my POST request.
