### ISSUE TITLE
How to get username and password from http Post request?

### ISSUE THREAD

**Issue by wdquan1985** [jfrog/artifactory-user-plugins#242]
This is my execution user plugin.
`executions {
serviceParameters { params, ResourceStreamHandle body ->

println "Debug: the first parameter: " + params['type'] //add,delete,update,search

println "Debug: the first parameter: " + params['repo']

println "Debug: the second parameter: " + params['webservice']

assert body

def json = new JsonSlurper().parse(new InputStreamReader(body.inputStream))
}`

Invoke the this plugin
-bash-4.2$ curl -X POST -v -u admin:password "http://10.243.82.228:8084/artifactory/api/plugins/execute/serviceParameters?params=type=search;repo=rpmtest;webservice=~~~~~~"

In my curl linux command, I have input the username and password.
I want to get the username and password in my execution user plugin, but I found it difficult to get it.
Could you provide one method to get it?

**Comment by DarthFennec** [comment]
The username and password are encoded and set in a header. You can get the headers from the thread context like this:

``` groovy
import org.artifactory.request.RequestThreadLocal

// ...

def tctx = RequestThreadLocal.context.get().requestThreadLocal
def auth = tctx.request.getHeader('Authorization')
```

Now, `auth` contains your encoded credentials. You can decode them using something like this:

``` groovy
def match = auth =~ "Basic\\s+(.*)"
def decoded = new String(match[0][1].decodeBase64())
def (username, password) = decoded.split(":")
```

**Comment by wdquan1985** [comment]
@DarthFennec @elioengcomp Thanks, my case only use the user name and I can get the it in my code now.
