### ISSUE TITLE
The Cleanup doesn't work

### ISSUE THREAD

**Issue by thilakpv** [jfrog/artifactory-user-plugins#244]
Hi,

I have the plugin installed in our artifactory server and when I run the curl command, I see the script won't return back to prompt and northing seems to be executing. Please advise

[root@cskpcloudxp1600 conf.d]# curl -X POST -v -u admin:password "http://localhost:8081/artifactory/api/plugins/execute/cleanup?params=months=1;repos=libs-release-local;dryRun=true;paceTimeMS=2000;disablePropertiesSupport=true"
* About to connect() to localhost port 8081 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
* Server auth using Basic with user 'admin'
> POST /artifactory/api/plugins/execute/cleanup?params=months=1;repos=libs-release-local;dryRun=true;paceTimeMS=2000;disablePropertiesSupport=true HTTP/1.1
> Authorization: Basic YWRtaW46QVA3UDdaSlFoblNzZXpFd1lWd3hLYkROUmVB
> User-Agent: curl/7.29.0
> Host: localhost:8081
> Accept: */*
> 

It doesn't return back after this

**Comment by thilakpv** [comment]
`[root@cskpcloudxp1600 conf.d]# curl -X POST -v -u admin:AP7P7ZJQhnSsezEwYVwxKbDNReA "http://localhost:8081/artifactory/api/plugins/execute/cleanup?params=months=1;repos=libs-release-local;dryRun=true;paceTimeMS=2000;disablePropertiesSupport=true"
* About to connect() to localhost port 8081 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
* Server auth using Basic with user 'admin'
> POST /artifactory/api/plugins/execute/cleanup?params=months=1;repos=libs-release-local;dryRun=true;paceTimeMS=2000;disablePropertiesSupport=true HTTP/1.1
> Authorization: Basic YWRtaW46QVA3UDdaSlFoblNzZXpFd1lWd3hLYkROUmVB
> User-Agent: curl/7.29.0
> Host: localhost:8081
> Accept: */*
> 

`

**Comment by elioengcomp** [comment]
Hi @thilakpv ,

Thank you for reaching out.

Can you see anything related to the cleanup plugin or your request in Artifactory logs?

Best.
Elio

**Comment by thilakpv** [comment]
Hi Elio,

I don't see any logs for the request.

**Comment by thilakpv** [comment]
I see the username "admin" not found in my LDAP, however I fixed it and changed to LDAP user and I still don't see anything on the logs

**Comment by elioengcomp** [comment]
Can you `touch` the plugin file or do a minor change to update the last modified date, call the reload plugin API at `/api/plugins/reload` and check the logs to confirm the plugin is being loaded successfully?

**Comment by renguomin** [comment]
I have the similar problem. I used artifactCleanup.groovy without any change. I used this command:

curl -i -u admin:password -X POST "http://xxxxxxx/artifactory/api/plugins/execute/cleanup?params=timeUnit=day;timeInterval=1;repos=installer-libs;dryRun=false;paceTimeMS=2000;disablePropertiesSupport=true"

This is the return on terminal:

HTTP/1.1 200 OK
Server: Artifactory/5.8.4
X-Artifactory-Id: 5d59042bf766283a:61f4a028:166a36233c7:-8000
Content-Type: text/plain
Content-Length: 0
Date: Wed, 24 Oct 2018 16:43:32 GMT


however, nothing shows up in the system log. And no artifacts has been deleted.

**Comment by elioengcomp** [comment]
Hi @renguomin 

Have you changed the verbosity for this plugin log at your `etc/logback.xml` file? 

You should have an entry like this:

```
<logger name="artifactCleanup">
    <level value="debug"/>
</logger>
```

Changing this file DOES NOT require you to restart Artifactory. You should see a log entry showing that the logging configuration changes caused it to be reloaded by Artifactory.

**Comment by renguomin** [comment]
BTW, I tried modifed the plugin and reload, this showed up in the log:

2018-10-23 16:41:49,647 [http-nio-8081-exec-9] [INFO ] (o.a.a.p.GroovyRunnerImpl:298) - Script 'artifactCleanup' loaded.

however, same thing happened when I execute the plugin, no log and nothing was done.

**Comment by elioengcomp** [comment]
By default Artifactory will show every `WARN` or higher level log messages. Even if you do not declare the plugin logger at you logback.xml file. 

Looking at the plugin source code it seems that most of its messages uses `INFO` log level. That is why you cannot see the messages at your artifactory.log file.

To see those messages you should set the log level for this plugin to `info`.
