### ISSUE TITLE
Using artifactCleanup.json - setting standard cleanup? 

### ISSUE THREAD

**Issue by gmarquez** [jfrog/artifactory-user-plugins#247]
Question: If cleanup policies are enabled for specific repos, how do you set the default for all others as the global/default? 

I currently have Logging working and so far cleanup of:
- project-a-releases-local retention = 7 years (keep for 7 years) 
- project-b-staging-local retention = 3 days (cleanup large debug binaries/builds frequently) 

I was unsure how to set the "standard cleanup" policy like before, where you define: months for ALL * other repos that are not defined in artifactCleanup.json. 

        {
            "cron": "0 30 1 ? * 1",
            "repos": [
                "project-a-releases-local"
            ],
            "timeUnit": "year",
            "timeInterval": 7,
            "dryRun": false,
            "paceTimeMS": 500,
            "disablePropertiesSupport": true
        },
        {
            "cron": "0 30 1 ? * 1",
            "repos": [
                "project-b-staging-local"
            ],
            "timeUnit": "days",
            "timeInterval": 3,
            "dryRun": false,
            "paceTimeMS": 500,
            "disablePropertiesSupport": true
        }

How or where could I add all others not defined in policy to use standard 30-day cleanup policy? 
e.g. apply policies defined in artifactCleanup.json ELSE cleanup * after 30-days.

I see the 2 policies running, no cleanup for project-a as expected and project-b deleting/cleanup after 3-days. However ALL other repos nothing seems to be done as any default policy.  

*Previously was set in: artifactCleanup.config as:
defaults = [
    build: 30,
    nonbuild: 1,
]

**Comment by gmarquez** [comment]
I have re-read the README.md file several times and it's unclear to me how to enable this for all others not defined in policies (as before). Perhaps this is more of a documentation update request to help clear up how to set this?

**Comment by DarthFennec** [comment]
As far as I'm aware, this was never a feature of this plugin to begin with. I've gone through the commit history, and I can't find any mention of it in the code. It's likely that the plugin you have was modified in-house by someone in your company, and that's why it allows this feature.

The concept of a "default cleanup policy" strikes me as an accident waiting to happen. I'd instead suggest just creating a regular policy, and adding new repos to it as needed. Is there a reason this isn't an option? What's your use case?

**Comment by gmarquez** [comment]
Thanks for reply. Sorry my mistake, this default parameter (which allows for a default * all/else to cleanup) I just found out it was a fork of the previous artifactCleanup.config.

I do understand the accident waiting to happen here. Let me explain the use-case: 
Because we dont have an unlimited amount of space, we have a policy for our artifactory. We allow some repos (release & other critical ones) to have longer retention periods: 7-10+ years. We require requests from end-users with justification. These repos are added into the artifactCleanup.config with the longer cleanup periods (7-10+ yrs). All else * will receive the standard 30-day cleanup. 

We document this policy and try to make all admins/users aware for any new repos which are created. From time to time, yes some users inform us about deletions. We point out the policy again and request the justification and apply the repo to the longer retention policies (in artifactCleanup.config), etc.

**Comment by gmarquez** [comment]
hi, since I guess we're not talking apples-to-apples here, we can cancel or close this issue and I'll re-use what was forked previously. 

@DarthFennec, or anyone else, 
I am interested to know about our use-case and the way we utilize the artifactCleanup plugin, any feedback? 

I like the newer .json update/style so wondering if perhaps in the future there is chance for this to be used this way? I think it would be great if it worked the way it does now with the "option" to include a global/default to all * other repos to have standard cleanup policy, of course knowingly accepting the risk and manually enabling it / turning it on. 

example:
# releases: 
- repo or list of repos: X timeUnit (years for longer retention)
# daily builds, etc: 
- repo or list of repos: X timeUnit (days for shorter retention)
# all others: 
- * : default (30-days)

**Comment by gmarquez** [comment]
or not... will close instead.
