### ISSUE TITLE
Archive old artifacts based on some condition

### ISSUE THREAD

**Issue by mohitkumarsharmaflux7** [jfrog/artifactory-user-plugins#248]
Label: Usecase

@elioengcomp   Is there any way to archive all the artifacts except x latest artifacts?
that means we have many ways to find the items in artifactory to select using `items.find({"modified" : {"$last" : "3d"}}) ` but we don't have a way to exclude something from this find operation.

Basically, i want to delete all the docker images from an artifactory repository except top 3 latest docker images. and the directory structure is nested that means 1--->2---->then docker images,  so is there way to do it using artifactory-user-plugins

**Comment by elioengcomp** [comment]
Hi @mohitkumarsharmaflux7 

I believe you can achieve that using [cleanDockerImages](https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup/cleanDockerImages) plugin.

**Comment by ankushchadha** [comment]
Hi @mohitkumarsharmaflux7, we will be closing this issue. Thanks.
