### ISSUE TITLE
[Bug] artifactCleanup cron stuck in execution loop (docker artifactory)

### ISSUE THREAD

**Issue by taylorsmcclure** [jfrog/artifactory-user-plugins#249]
**Artifactory Version**: artifactory-pro-5.8.4 (docker container)

**Background info**: We run artifactory pro in a container with a bind mount for data/configuration persistence.

**Problem**: `art-exec` became stuck in an infinite loop executing the `artifactCleanup` plugin after setting a cron job as `* * * * * ?` in `artifactCleanup.json`

**Policy file contents**:
```
{
    "policies": [
        {
            "cron": "* * * * * ?",
            "repos": [ "repo" ],
            "dryRun": false,
            "timeUnit": "day",
            "timeInterval": 10,
            "paceTimeMS": 1000,
            "disablePropertiesSupport": true
        }
    ]
}
```

**Expected Behavior**: After removing `artifactCleanup.*` files and executing `/api/plugins/reload` the plugin will stop executing every second. Also tried plugin specific stop request: `api/plugins/execute/cleanupCtl?params=command=stop"` but did not stop execution of the plugin. Both the reload and stop API requests were confirmed to be received in the system logs.

**Resolution**: I had to `docker restart ...` the container bringing down artifactory for my org.

**Additional information**: Curiously I was having trouble getting artifactory to pickup changes to `artifactCleanup.json`, I found that I needed to fully remove `etc/plugins/artifactCleanup*` files, reload the plugins through the API, then add the files again with the updated values. My suspicion would be how artifactory picks up filesystem changes since in this case the directory was on a bind mount.

**Comment by taylorsmcclure** [comment]
Hi @elioengcomp, thank you for getting back to me so quickly.

Sorry I think I was a little unclear as to why I scheduled it to run every second. This was purely for troubleshooting purposes (I have the job running once per night). The original issue was the plugin was stuck in `dryRun: true` after explicitly setting it `false` and reloading the plugins.

I think the crux of the issue is `art-exec` had the `artifactCleanup.json` settings in memory and refused to let go of it even after a reload plugins API call. Since I was able to resolve this issue myself, I figured I would open this as a bug report. Shall I still open a support case to report the bug?

**Comment by elioengcomp** [comment]
I think it is still relevant to open the support ticket as a bug report and close this Github issue, since it looks more like an Artifactory/environment issue than a problem with the plugin itself. 

If there is an issue on reloading plugins when the plugins folder is on a bind mount, the support team can help to identify.

**Comment by taylorsmcclure** [comment]
Sounds good to me! Thank you @elioengcomp
