### ISSUE TITLE
Feature Request: Helm Push Plugin for Helm CLI using Artifactory

### ISSUE THREAD

**Issue by dbluxo** [jfrog/artifactory-user-plugins#256]
Could you please provide a Helm Push Plugin for Helm CLI using Artifactory.

Such as for ChartMuseum: https://github.com/chartmuseum/helm-push

**Comment by mrballcb** [comment]
I created a Jenkins pipeline function that I pass some values to it that runs a shell function that does this:
```
           helm package --save=false ${extraArgs} ${PROJ}
           ls -l ${PROJ}-${PackageVersion}.tgz
           MD5SUM=\$(md5sum ${PROJ}-${PackageVersion}.tgz | awk '{print \$1}')
           SHA1SUM=\$(sha1sum ${PROJ}-${PackageVersion}.tgz | awk '{print \$1}')
           SHA256SUM=\$(sha256sum ${PROJ}-${PackageVersion}.tgz | awk '{print \$1}')
           if [ "${Publish}" = "true" ]; then
             curl -XPUT --user ${env.USERNAME}:${env.PASSWORD} \
               --upload-file ${PROJ}-${PackageVersion}.tgz \
               -H"X-Checksum-Sha256:\${SHA256SUM}" \
               -H"X-Checksum-Sha1:\${SHA1SUM}" \
               -H"X-Checksum-Md5:\${MD5SUM}" \
               https://${ArtifactoryHostname}/helm/${PROJ}-${PackageVersion}.tgz
             # Re-index helm repo
             curl -v -XPOST --user ${env.USERNAME}:${env.PASSWORD} \
               https://${ArtifactoryHostname}/api/helm/helm-local/reindex
           fi
```

So such a plugin would really only need to do something like that.

**Comment by ankushchadha** [comment]
In Helm V2, we recommend using the JFrog CLI to push helm charts. But if there is a need for a helm plugin, and if we can get more votes, then we can definitely prioritize it. 

However, in helm v3, there will be an official push cmd supported by the helm CLI - https://github.com/helm/community/pull/57

**Comment by dbluxo** [comment]
@ankushchadha Would be great if you could provide a helm plugin!

**Comment by dbluxo** [comment]
Luckily @miguel-santiago has implemented this feature in his plugin: https://github.com/belitre/helm-push-artifactory-plugin/issues/1
