### ISSUE TITLE
Update artifactCleanup README to point to the cleanDockerImages plugin

### ISSUE THREAD

**Issue by patbat95008** [jfrog/artifactory-user-plugins#259]
Currently the artifactCleanup plugin works well for all Artifactory repositories except Docker.  Deleting a Docker layer based on their last download date might cause issues cleaning up, as not all layers need to be downloaded during a "docker pull."

There should be a link in the [artifactCleanup README](https://github.com/jfrog/artifactory-user-plugins/blob/master/cleanup/artifactCleanup/README.md) to point to the[ cleanDockerImages user plugin,](https://github.com/jfrog/artifactory-user-plugins/tree/54406c38b1c7f91c265ab11cc38aefeb45cbdd4b/cleanup/cleanDockerImages) which is the recommended way to clean up Docker images based on download times.

**Comment by elioengcomp** [comment]
@patbat95008 would you mind submitting a PR with that change?

**Comment by ankushchadha** [comment]
Hi @patbat95008, can you submit the PR? 

Thanks
