### ISSUE TITLE
How to pass a JSON body using the url parameter provided by webhook plugin

### ISSUE THREAD

**Issue by tayebBenAchour** [jfrog/artifactory-user-plugins#263]
Hello,

I cannot find anywhere a way to send a http request with a JSON body using the webhook plugin.
Any help would be appreciated. :)

**Comment by elioengcomp** [comment]
Hi @tayebBenAchour 

The plugin will automatically send a POST HTTP request with a JSON payload according to the rules you set in the `webhook.config.json` file.

**Comment by ankushchadha** [comment]
Hi @tayebBenAchour, we are closing this issue since the answer was provided. 

Thanks
