### ISSUE TITLE
conda checksum

### ISSUE THREAD

**Issue by hrzafer** [jfrog/artifactory-user-plugins#264]

**Comment by hrzafer** [comment]
Hi,

We're using Artifactory v6.1 and upgrade is not an option for now. Therefore, we are using conda plugin. It works as expected but when we deploy a package with `curl`, we see the following error on web panel.

```Client did not publish a checksum value.
If you trust the uploaded artifact you can accept the actual checksum by clicking the 'Fix Checksum' button.
```

Except this warning everything seems working. I wonder why we get this warning.

**Comment by elioengcomp** [comment]
Hi @hrzafer,

The reason why you see that warning is because a checksum was not provided by the client during the deployment. 

You can learn more about it [here](https://jfrog.com/knowledge-base/what-are-client-checksum-server-checksum-and-checksum-policy-in-local-repositories/).

Best.
Elio

**Comment by hrzafer** [comment]
Hi @elioengcomp,

Thanks for the quick response. I was able to upload the package successfully as suggested in the document. This [SO answer](https://stackoverflow.com/a/40009689) also explains how to generate the checksum as follows:

```
CHECKSUM=$(md5sum foo.zip | awk '{ print $1 }')

curl --header "X-Checksum-MD5:${CHECKSUM}" --upload-file "foo.zip -u "admin:<apikey>" -v https://artifactory.example.com/foo/
```

**Comment by elioengcomp** [comment]
I'm glad to help!

**Comment by hrzafer** [comment]
Hi again,

I realized that we have the same issue with packages coming from remote public conda repo https://repo.continuum.io/pkgs/main/. We don't have any control over this deployment process. The plugin does that. How can we resolve this without pressing the `Fix Checksum` button for every single package?

Thanks,

**Comment by elioengcomp** [comment]
Hi @hrzafer,

We don't need to worry about setting the properties at the *-cache repos.

**Comment by hrzafer** [comment]
@elioengcomp No. We can still consume contents of the repo.

**Comment by elioengcomp** [comment]
@hrzafer,

I believe the warning you see for the remote repo is a UI bug in Artifactory. Since it does not affect the usage of the repo neither the plugin, I think it is safe to ignore it. 

If you want to know more about it, because it is an Artifactory related issue/question, not a plugins one, I encourage you to open a ticket with the support team to provide you more information about that. They may file a bug to the Artifactory team if needed.

**Comment by ankushchadha** [comment]
Hi @hrzafer, we are closing this issue. Let us know if there are any other questions. Thanks.
