### ISSUE TITLE
webhook: Filter docker events by tag

### ISSUE THREAD

**Issue by smorehouse** [jfrog/artifactory-user-plugins#266]
nokia/artifactory-user-plugins#1

This change allows you to filter docker events by tag. This is set in the existing path variable in webhook.config.json:
"path": "os_base/centos:latest"

Any change to other tags will be ignored.

**Comment by elioengcomp** [comment]
Hi @smorehouse 

Thank you for opening this issue. Your proposal seems to be a useful feature and a nice addition to the webhook plugin. 

I can see that you already have a pull request created against a fork of this repo. Would you mind creating the pull request against this repo, so we can review and merge it?

Also, in case you have not signed our CLA yet, would you mind doing so as described in the [CONTRIBUTING.md](https://github.com/jfrog/artifactory-user-plugins/blob/master/CONTRIBUTING.md)

**Comment by smorehouse** [comment]
Unfortunately my company will not let me sign the CLA so I have to propose
changes via this mechanism. I don’t really understand it I’m just doing
what I’m told.

**Comment by elioengcomp** [comment]
No problem. 

I'm creating an internal task for us to promote your PR to this repo.  

Thanks again for the contribution.

**Comment by smorehouse** [comment]
You're welcome, sorry again for the complication this causes. I have a couple of other contributions I'd like to commit as well. First is adding logging, and the second is support for a JenkinsFormatter so Jenkins jobs can be triggered via webhook. Are these things you would be interested in?

**Comment by elioengcomp** [comment]
Sure! However, it would be very nice if you could send those PRs against the official repo so you could take the credits for those contributions and have you user tagged as a Contributor for this repo.

**Comment by smorehouse** [comment]
I'd love for that to be the case, but I have to follow what my employer is allowing me to do.

**Comment by smorehouse** [comment]
@elioengcomp any updates?

**Comment by ankushchadha** [comment]
Hi @smorehouse, thank you for suggesting this change. This will help a lot of users.

We have scheduled this after our user event SwampUp (June 17 - June 20). Tests need to be added by us before we uptake this change.

@markgalpin - FYI

**Comment by CsatariGergely** [comment]
@ankushchadha great, thanks. Do you have any idea when this will get in?

**Comment by DarthFennec** [comment]
Looks good to me, I've merged and added tests. Thanks!
