### ISSUE TITLE
Unable to see contribution agreement

### ISSUE THREAD

**Issue by Krijger** [jfrog/artifactory-user-plugins#267]
I would like to contribute, but I am unable to see the agreement you need to sign. Tested in Firefox and Chrome I get:

![Screen Shot 2019-03-14 at 16 20 30](https://user-images.githubusercontent.com/3886732/54369035-7c2db900-4675-11e9-921d-4d9b14093cc6.png)

which is of course unsignable.

**Comment by DarthFennec** [comment]
Yeah that's unsignable. I can reproduce, debug console says it's a CORS issue. I don't think that's under our control, likely some kind of bug in echosign or something? @elioengcomp Is there an alternative procedure that can be used? If this persists too long it might also be best to use a different service, too.

**Comment by elioengcomp** [comment]
I asked @markgalpin to help us with that.

**Comment by elioengcomp** [comment]
Hi @Krijger,

It should be fixed now. Can you try again?

**Comment by Krijger** [comment]
The PR for which I needed this will not continue as a valid alternative to
my proposed solution was mentioned there. This story was meant to let you
know; I trust your testing capabilities.

Regards

Op wo 27 mrt. 2019 om 19:17 schreef Elio Marcolino <notifications@github.com

**Comment by elioengcomp** [comment]
Got it! I'm closing this issue then.
