### ISSUE TITLE
"org.jfrog.lilypad.Control" package is missing

### ISSUE THREAD

**Issue by achana-anz** [jfrog/artifactory-user-plugins#270]
I am working to setup development environment to run/debug WebhookTest and unable to resolve ""org.jfrog.lilypad.Control" package.

Following maven dependancy is used to fetch this and unable to find this package
```
<dependency>
      <groupId>org.jfrog.artifactory.client</groupId>
      <artifactId>artifactory-java-client-services</artifactId>
      <version>2.5.1</version>
      <exclusions>
        <exclusion>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by DarthFennec** [comment]
Some of the tests for some of the plugins in this repo utilize features of our internal testing framework, Lilypad. There was conversation at some point to make Lilypad publicly available, but nothing ever came of that. I expect it might be possible to modify the tests to work without that import, but beyond that I don't think you'll be able to run them.

Could you explain what you're trying to do? Perhaps there's a different approach that might work better for you.

**Comment by achana-anz** [comment]
Thanks for the quick response.

My requirement is to update/customise existing Webhook plugin to return a JSON that compatible with our backend system.  So I want to set up and run/debug existing code as a starting point of the change.


```
{
    "artifacts": [
      {
        "type": "animal",
        "name": "dog",
        "version": "1.0.0",
        "reference": "animal/dog
      }
    ]
}  
```

**Comment by DarthFennec** [comment]
Makes sense. Well as far as I can tell, the Lilypad calls are used primarily to write variations of configuration files to Artifactory's filesystem, in order to test different aspects of the plugin. It's also used to deploy a supplementary plugin that acts as the webhook client, but it's the same idea. You could try replacing these calls with direct filesystem calls, e.g. via [`java.io.File`](https://docs.oracle.com/javase/8/docs/api/java/io/File.html) and friends.

**Comment by achana-anz** [comment]
Thanks for the details earlier . I am in the process of populate following values based on "Artifactory Public API" model : http://repo.jfrog.org/artifactory/oss-releases-local/org/artifactory/artifactory-papi/%5BRELEASE%5D/artifactory-papi-%5BRELEASE%5D-javadoc.jar!/index.html . Could you please guide me to populated **artifact name, version and download URL**?

I can see the name and version values under FileLayoutInfo properties in Artifactory WEB UI (Chart.name :my-app , Chart.version: 0.1.0 ), but I am not able to retrieve back it via API model mentioned above. 

```
{
    "artifacts": [
      {
        "type": "helm/chart",
        "name": "my-app",
        "version": "0.1.0",
        "reference": "http://localhost:8081/artifactory/helm-local/my-app-0.1.0.tgz"
      }
    ]
}
```

**Comment by DarthFennec** [comment]
First you probably need a [`RepoPath`](http://repo.jfrog.org/artifactory/oss-releases-local/org/artifactory/artifactory-papi/%5BRELEASE%5D/artifactory-papi-%5BRELEASE%5D-javadoc.jar!/org/artifactory/repo/RepoPath.html). Depending on the plugin hook you're working in, it might pass you an appropriate `RepoPath`, or else a `FileInfo`/`ItemInfo` (from which you can get a `RepoPath` by doing `info.getRepoPath()`). Alternatively, you can make a `RepoPath` using [`RepoPathFactory.create()`](http://repo.jfrog.org/artifactory/oss-releases-local/org/artifactory/artifactory-papi/%5BRELEASE%5D/artifactory-papi-%5BRELEASE%5D-javadoc.jar!/org/artifactory/repo/RepoPathFactory.html), and passing a repo name and a path string.

Once you have your `RepoPath`, you can use the built-in [`repositories`](http://repo.jfrog.org/artifactory/oss-releases-local/org/artifactory/artifactory-papi/%5BRELEASE%5D/artifactory-papi-%5BRELEASE%5D-javadoc.jar!/org/artifactory/repo/Repositories.html) object to get the information you need via a `LayoutInfo` object, like so:

``` groovy
def layoutinfo = repositories.getLayoutInfo(repoPath)
def name = layoutinfo.getModule()
def version = layoutinfo.getBaseRevision()
```

I haven't tried this with Helm repos specifically, but it should work alright.

There isn't a function for getting the download URL, but you can easily build it:

``` groovy
def url = "http://localhost:8081/artifactory/" + repoPath.toPath()
```

**Comment by achana-anz** [comment]
Thank you very much for the quick response. 

I tried as describe above but it was not successful. Both **layoutinfo.getModule() and layoutinfo.getBaseRevision()** returned null.

Then, I further analysed on how the Artifactory WEB UI fetch these values and notice that it is based on "Artifact" Is this  org.artifactory.build.Artifact ?  How to retrieve Artifact object (I can't find much details under documentation )

WEB UI fetch these details via below REST API 

```
Request URL: http://localhost:8081/artifactory/ui/artifactproperties?path=my-app-0.1.0.tgz&repoKey=helm-local

{"artifactProperties":[{"name":"chart.name","value":"my-app"},{"name":"chart.description","value":"A Helm chart for Kubernetes"},{"name":"chart.version","value":"0.1.0"},{"name":"chart.appVersion","value":"1.0"}]}  

--- Attached the reference screenshot 

````

```
and : Request URL: http://localhost:8081/artifactory/ui/artifactgeneral

{"type":"file","info":{"name":"my-app-0.1.0.tgz","repositoryPath":"helm-local/my-app-0.1.0.tgz","moduleID":"N/A","deployedBy":"admin","size":"2.91 KB","created":"15-04-19 17:36:23 +10:00","lastModified":"15-04-19 17:39:34 +10:00","licenses":[{"name":"Not Found","approved":false}],"downloaded":0,"remoteDownloaded":0,"showFilteredResourceCheckBox":true,"filtered":false},"virtualRepositories":[{"repoKey":"helm-virtual","linkUrl":"http://localhost:8081/artifactory/helm-virtual"}],"checksums":{"sha2":"SHA-256: 094ac555290f756c547523322b72036f0a5507b9bf2c9f16d1d15ed0dfef6460 (Uploaded: Identical)","sha1":"SHA-1: 5f80914e775ee41b98b995233fe86b2f854dc88f (Uploaded: Identical)","sha1Value":"5f80914e775ee41b98b995233fe86b2f854dc88f","md5":"MD5: e01f5c37a5cc730d66d36b45f75ac48e (Uploaded: Identical)","showFixChecksums":false},"bintrayInfoEnabled":false}
```
![Screen Shot 2019-04-16 at 1 24 05 pm](https://user-images.githubusercontent.com/48973533/56180490-e65ac480-604c-11e9-9f81-96609a7ce928.png)


Could you please guide me on how to retrieve same based on  "Artifactory Public API" model

**Comment by DarthFennec** [comment]
I see. I was describing how to do it via the layout-based system that many repo types use, where the name and version information is encoded into the artifact path. It looks like Helm stores that information as properties, instead. So we can just do this:

``` groovy
def name = repositories.getProperty(repoPath, "chart.name")
def version = repositories.getProperty(repoPath, "chart.version")
```

**Comment by achana-anz** [comment]
Thanks for your information.

Unfortunately, these properties are not available during "storage.afterCreate" event. Our requirement is to populate JSON payload on "storage.afterCreate" event and send to the configured URL. Hence, I did a regex implementation to read name and version form "item.name". 

Separately, I have completed the customisation and successfully tested our environment.  I created a pull request. https://github.com/jfrog/artifactory-user-plugins/pull/273/files 
Please do a review and let me know your feedback.

**Change summary : A POST formatted specifically for Spinnaker**
Extended Webhook plugin to support Helm and Docker repositories to generate Webhook payload as per the spinnaker specification. This will allow automating the deployment process integrating with Spinnaker.  https://www.spinnaker.io/guides/user/pipeline/triggers/webhooks/


Docker Support:  https://www.spinnaker.io/reference/artifacts/types/docker-image/
 
``` json
{
  "artifacts": {
    "type": "docker/image",
    "name": "myapp",
    "version": "latest",
    "reference": "http://localhost:8081/artifactory/docker-local/myapp:latest"
  }
}
```

Helm Support :  This plugin will generate JSON Payload as per Spinnaker specification.
 
``` json
{
  "artifacts": {
    "type": "helm/chart",
    "name": "myapp",
    "version": "1.1.7",
    "reference": "http://localhost:8081/artifactory/helm-local/myapp-1.1.7.tgz"
  }
}
```

Sample configuration is as follows

``` json
{
  "webhooks": {
    "helm": {
      "url": "Spinnaker Webhook URL for HELM",
      "events": [
        "storage.afterCreate"
      ],
      "path": "*.tgz",
      "format": "spinnaker"
    },
    "docker": {
      "url": "Spinnaker Webhook URL for Docker",
      "events": [
        "docker.tagCreated"
      ],
      "format": "spinnaker"
    }
  },
  "debug": false,
  "timeout": 15000,
  "baseurl": "Artifactory BaseURL",
  "enablespinnakersupport": true
}
```

**Comment by achana-anz** [comment]
Hi DarthFennec, 

Hope you are well. 

Did you get a chance to review my pull request?  

Regards,
Achana
