### ISSUE TITLE
How do we integrate this plugin?

### ISSUE THREAD

**Issue by praveen4682** [jfrog/artifactory-user-plugins#275]
we have artifactory instance(https://repo-l.east1.ncloud.netapp.com).I didn't find steps on how to integrate this plugin(https://github.com/jfrog/artifactory-user-plugins/tree/master/storage/createCopy) 
with our artifactory instance.it would be great if you can help us.Thanks.

**Comment by DarthFennec** [comment]
Documentation on deploying plugins can be found [here](https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-DeployingPlugins).

To summarize, copy the `createCopy.groovy` and `createCopy.properties` files into the `${ARTIFACTORY_HOME}/etc/plugins` directory (create the directory if it doesn't exist). Edit the `createCopy.properties` file to suit your needs, as described in the plugin's [readme](https://github.com/jfrog/artifactory-user-plugins/blob/master/storage/createCopy/README.md) file. Then, you can load the plugin by running the [reload plugins REST endpoint](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ReloadPlugins) or by restarting Artifactory.

Let us know if you need further details. Thanks!

**Comment by ankushchadha** [comment]
Hi @praveen4682, we are closing this issue since the documented steps were provided.
