### ISSUE TITLE
Please help in making artifactCleanup plugin to accept specific path

### ISSUE THREAD

**Issue by heavymevi** [jfrog/artifactory-user-plugins#276]
Currently, the artifactCleanup user plugin works only for repositories and not for specific paths.
it will be more helpful to use this plug in with specific path

**Comment by DarthFennec** [comment]
Apologies for the late reply. This does seem very useful! You say "Please help in making", does that mean you plan to make this change yourself but you need our help to do it, or are you asking for us to make the change? Either is fine, but in case of the former, can you give more details on what you need help with? Thanks.

**Comment by mahindia** [comment]
Hi, Thank you for the reply. We would like you to add the additional functionality of allowing the Artifactory Cleanup plugin to search only inside the given folders and not at the repository level. Current functionality of the artifact cleanup plugin allows to search for artifacts throughout the repository, but not within a specific folder inside a repository.

**Comment by harendrar8095** [comment]
Thanks for bringing this up!

As you can see in [our documentation](https://jfrog.com/help/r/jfrog-platform-administration-documentation/package-types-coverage), we are working on a newer, recommended way to extend the JFrog Platform (including Artifactory) in a cloud-native way, called JFrog Workers. Unfortunately, this means that our focus and resources are directed toward that initiative, and we are not able to review and approve new PR or feature request at this time.


We’re closing this for now, but feel free to reopen it if you have any further queries!
