### ISSUE TITLE
Ambiguous expression could be either a parameterless closure expression or an isolated open code block

### ISSUE THREAD

**Issue by mehstg** [jfrog/artifactory-user-plugins#281]
have a webhook.config.groovy file as follows:
`{
        "webhooks": {
                "syncRepos": {
                        "url": "https://jenkins-server/buildByToken/build?job=tools/sync-repos&token=mytoken",
                        "events": [
                                "docker.tagCreated"
                        ],
                        "repositories": [
                                "ci"
                        ]
                }
        },
        "debug": true,
        "timeout": 15000

}`

As far as I can see from the documentation, this should be valid, and should fire whenever a tag is created in the 'ci' repository.

I am seeing the following stacktrace in the catalina.out file when reloading plugins via the API:
`2019-07-12 09:00:51,980 [http-nio-8081-exec-43] [ERROR] (o.a.a.p.GroovyRunnerImpl:328) - Error loading script from '/var/opt/jfrog/artifactory/etc/plugins/webhook.config.groovy'.
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/var/opt/jfrog/artifactory/etc/plugins/webhook.config.groovy: 1: Ambiguous expression could be either a parameterless closure expression or an isolated open code block;
   solution: Add an explicit closure parameter list, e.g. {it -> ...}, or force it to be treated as an open block by giving it a label, e.g. L:{...} @ line 1, column 1.
   {
   ^
`
We are running Artifactory 6.6.3 on Amazon Linux.

**Comment by elioengcomp** [comment]
Hi @mehstg ,

The configuration file for the webhook plugin should be a json file, not a groovy one.

Can you rename the file to `webhook.config.json` and try again?

**Comment by mehstg** [comment]
Hi there
Getting `2019-07-15 07:32:23,239 [art-exec-2] [ERROR] (webhook             :406) - Failed to load configuration from webhook.config.json. Verify that it is valid JSON` when I rename to JSON. The file lints OK.

**Comment by jfrog-aparicio** [comment]
Hello @mehstg ,

The json looks valid and loads on my end when I copy/paste it. Can you verify that there aren't any weird characters in the file? Maybe try copy/pasting it. If you are using HA, Artifactory will automatically copy the json to all the nodes, make sure it is correct in all of them.

Also note that if you are using api/plugins/reload, this will not pick up changes to the json file since it is only looking changes in groovy files. If you make changes only to the json file, use the 'api/plugins/execute/webhookReload' endpoint as described in the [README](https://github.com/jfrog/artifactory-user-plugins/tree/master/webhook#making-changes-to-the-configuration).

**Comment by damluji** [comment]
hello, i have run into the same issue. the JSON file is in the correct path and is readable by artifactory user, using the master branch of this webhook
as for artifactory, we are using version 
 Artifactory Enterprise
6.5.17 rev 60517900

**Comment by nikhilpathania** [comment]
Hi @damluji and @mehstg, I am facing the same issue, did you manage to find a solution?

**Comment by damluji** [comment]
hello @nikhilpathania , we had to upgrade artifactory to 6.16.2, and use this config

`{
  "webhooks": {
     "allStorageAndReplication": {
       "url": "YOUR WEBHOOK URL HERE",
       "events": [
         "storage.PUTYOUREVENTSHERE",
          .
          .
         "storage.MORESTUFF"
       ],
       "format": "slack"
     }
  }
}`
