### ISSUE TITLE
CancelException cancels the transaction. How to throw an exception without cancelling the transaction?

### ISSUE THREAD

**Issue by sarathkrishna2018** [jfrog/artifactory-user-plugins#287]
I have two curl commands to upload the artifact and then its properties. There is a reason why I needed two separate commands. Anyway, I'm writing a plugin to validate if a specific property key has a valid value. If the validation fails, I need to move the artifact to a backup repository, and also throw an exception. Throwing a CancelException cancels the entire transaction ( moving action ) as well. I need to return an exception to curl as Jenkins will be calling the command and I need Jenkins to know that the properties were not update and also that the artifact has been backed up. Any ideas?

**Comment by elioengcomp** [comment]
Hi @sarathkrishna2018,

Can you share the code you have so far so we can have a better picture of the approach you are using?

**Comment by sarathkrishna2018** [comment]
Hi @elioengcomp . Thanks for addressing. Here is the code.

`storage{
	
	beforePropertyCreate { ItemInfo item, String name, String[] values ->
	
	if(name.equalsIgnoreCase("ProperyKeyName"))
	{
		if(values[0].equalsIgnoreCase("ValidPropertyKeyValue")){
		println("FINE")
		}
		else{
		println("NOTFINE")
		asSystem {
			def destpath = RepoPathFactory.create("BACKUP-REPO", item.relPath)
			StatusHolder holder = repositories.move(item.repoPath, destpath)
            if (holder.error) {
			log.error "Failed to move"
			} else {
			throw new CancelException("Property value invalid. Uploaded artifact is moved to backup repository.", 409);
			}
			}
		}
	}
}
}`

Throwing that CancelException cancels the move operation as well. May be that is the intended behaviour, but I'm looking for a way to throw an exception to curl command line without cancelling the move operation.

**Comment by DarthFennec** [comment]
I'm not certain, but my guess is that the `CancelException` is rolling back the entire database transaction, which contains both the property create and move operations (any database-related operations would be cancelled in this case). This is probably not intended behavior.

The only way I'm aware of to escape the transaction is to create a new thread and perform the move there. That should prevent it from being cancelled.

**Comment by sarathkrishna2018** [comment]
Hi @DarthFennec thanks for your reply. I have called a curl command to move the artifact, and then threw the exception. It's working. But I'm afraid if this is a dirty solution though. Any comments on this workaround/solution?

**Comment by DarthFennec** [comment]
I think that's a fine solution. Spawning a thread to do it would be slightly more optimal, as it would bypass the network stack, but the code would probably be more complicated. And honestly that's still kind of a dirty solution, I don't think there is an ideal workaround for this.
