### ISSUE TITLE
mandate certain properties on artifact creation

### ISSUE THREAD

**Issue by ppraveenyadav** [jfrog/artifactory-user-plugins#289]
Hello,

Can we somehow mandate a certain property creation along with artifact upload ?
I have tried using beforePropertyCreate to do certain validation on property, but if i dont have the property itself, the validation doesnot work.

Thanks in Advance!!

**Comment by elioengcomp** [comment]
Hi @ppraveenyadav ,

I think you could try using [beforeUploadRequest](https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-Upload) to check if the properties where sent in the upload request.

Another alternative that might be worth a shot is [afterCreate](https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-Storage) to check if the properties were set as soon as the artifact was created.

**Comment by ppraveenyadav** [comment]
Thanks for the response !!!
We are making two different calls
1. To upload artifact
2. To push artifact properties

Somehow I'm now in a position, where I need to validate some properties which should be always passed in the request for 2nd API call.

I'm not sure if beforeUplaodRequest will be triggered even for only parameters update call.

But I will check the possibility with beforeUplaodRequest.

**Comment by elioengcomp** [comment]
Have you considered sending the properties with the upload call to do it on a single request? https://www.jfrog.com/confluence/display/RTF/Using+Properties+in+Deployment+and+Resolution

**Comment by ppraveenyadav** [comment]
@elioengcomp 
A bit of background, We are using gradle builds and directly publishing the artifact to artifactory within gradle builds.

2nd API call is something we are relying on properties update, but unable to validate the check whether mandatory properties are pushed or not.
:(

**Comment by elioengcomp** [comment]
How are you pushing the gradle artifacts to Artifactory? Are you using Artifactory gradle plugin or JFrog CLI to do it?

**Comment by ppraveenyadav** [comment]
- Yes, to push artifacts to artifactory we are using Artifactory Gradle Plugin.
- But to update custom properties for an artifact we are making a separate rest call to jfrog rest API.

**Comment by elioengcomp** [comment]
Using two different calls, I don't believe there is a way to enforce the properties are set during artifacts creation. There is a way to [set properties on artifacts](https://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin#GradleArtifactoryPlugin-TheArtifactoryProjectPublishTask) using the Artifactory Gradle Plugin. I believe that will attach the properties with the upload in a single call and allow you to rely on the `beforeUploadRequest`. If you want to keep the two operation however, another alternative would be to write a plugin with [job](https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-Jobs) that would periodically search for artifacts without the required properties and do something about them. It could be a basic reporting or even automatically demote them to a black list repo.

**Comment by ppraveenyadav** [comment]
We realized from mandating properties is something we cannot achieve but the whole discussion helped a lot.

Yes .. we are actually doing something close to your suggested second approach.

Thank for all quick responses and information.

**Comment by elioengcomp** [comment]
I'm glad to help.
