### ISSUE TITLE
user plugin 3th party dependencies jars did not load successfully

### ISSUE THREAD

**Issue by cw1427** [jfrog/artifactory-user-plugins#295]
I made a customer user plugin and it depends on http-builder jar which I put in the lib folder, but the plugin still load failed.  I start Artifactoy in docker.
error log
`2019-10-11 03:06:41,172 [art-init] [INFO ] (o.a.a.p.GroovyRunnerImpl:254) - Loading script from 'odm1_replicate_trigger_plugin.groovy'.
2019-10-11 03:06:41,250 [art-init] [ERROR] (o.a.a.p.GroovyRunnerImpl:310) - Error loading script from '/opt/jfrog/artifactory/etc/plugins/odm1_replicate_trigger_plugin.groovy'.
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/opt/jfrog/artifactory/etc/plugins/odm1_replicate_trigger_plugin.groovy: 8: unable to resolve class groovyx.net.http.ContentType
 @ line 8, column 1.
   import groovyx.net.http.ContentType
   ^

file:/opt/jfrog/artifactory/etc/plugins/odm1_replicate_trigger_plugin.groovy: 7: unable to resolve class groovyx.net.http.HTTPBuilder
 @ line 7, column 1.
   import groovyx.net.http.HTTPBuilder
   ^

file:/opt/jfrog/artifactory/etc/plugins/odm1_replicate_trigger_plugin.groovy: 9: unable to resolve class groovyx.net.http.Method
 @ line 9, column 1.
   import groovyx.net.http.Method
   ^

3 errors

        at org.`

-rw-rw-r-- 1 artifactory artifactory  1768 Mar 21  2018 internalUser.groovy
drwxr-xr-x 2 artifactory artifactory  4096 Oct 11 11:06 lib
-rw-r--r-- 1 artifactory artifactory  2762 Oct 10 18:09 odm1_replicate_trigger_plugin.groovy
root@:/var/opt/jfrog/artifactory/etc/plugins# cd lib/
root@:/var/opt/jfrog/artifactory/etc/plugins/lib# ls
http-builder-0.7.1.jar	json-simple-1.1.1.jar
json-lib-2.4-jdk15.jar	xml-resolver-1.2.jar
root@:/var/opt/jfrog/artifactory/etc/plugins/lib#

**Comment by DarthFennec** [comment]
I'm not sure what's going on, this certainly looks right. You could try running the [plugin reload API](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ReloadPlugins), which may or may not help (you might have to `touch` or modify the plugin file first for this to work). Beyond that, I guess make sure that you're using the correct jar file.

**Comment by cw1427** [comment]
Plugin reload API doesn't work. And I pretty much make sure the jars are correct. I doubt if the docker mode would be the reason, which I mounted the Artifactory path into container via volume.

BTW, I run the Artifactory in HA mode. 

And some weird things are, sometime I just deleted the plugin file and the jars under the lib folder. But they would apperaed again. It looks like the Artifactory had cached and restored them.

**Comment by DarthFennec** [comment]
You might need to run the reload API or delete the plugin files on all the nodes, instead of just one. But yeah, plugin files are saved to the database so they can be copied to the other HA nodes, but sometimes it'll do weird things like restore the files after they're deleted, or even create truncated/empty files instead of complete ones (this is a known bug). You could double check that the jars are the correct file size on all nodes, to make sure you're not encountering this.
