### ISSUE TITLE
Lack documentation in case of exception

### ISSUE THREAD

**Issue by sluongng** [jfrog/artifactory-user-plugins#296]
I would like to have additional information regarding a plugin behavior in case of exception happening mid plugin execution.

How does boolean base plugin (i.e. realms) behave, how does void ones behave?

Reference: https://www.jfrog.com/confluence/display/RTF/User+Plugins

**Comment by sluongng** [comment]
just an update: the plugin kinda failed silently without log/warn/anything

So at the very least I would suggest to wrap plugin execution with a try catch and exception logged with proper stack trace. (this could be toggle by a feature flag)

**Comment by DarthFennec** [comment]
Weird, if an exception is thrown it should always log a stacktrace at least. The only time I've seen a silent failure like that is when the plugin spawns a new thread, and an uncaught exception is thrown in that thread.

I believe if an exception is thrown in a realm plugin, it's equivalent to a failure to authenticate (so, it moves on to try the next realm). I'd have to double check though. I'm not sure what you mean by "void ones", can you elaborate?

**Comment by sluongng** [comment]
@DarthFennec "void ones" are just User Plugins with 'void' as return type.

But yeah, in my experience debugging these User Plugin execution, even with a logback.xml config for the plugin at debug level, we get not exception logging (tested with authentication realms)

The current work around is to wrap everything with a try/catch and delegate to a safe default behavior on exception.

I would suggest adding into documentation regarding these default behavior on exception. (i.e. if you implement an auth plugin, what would be the default behavior when exception happen, will the request go to LDAP as fallback? etc..)

**Comment by nehamjfrog** [comment]
Thank you for this feature request. We appreciate all user input. However, since this request has been dormant for some time and several plugins have been deprecated in the latest releases, we are closing it for now. If you have any updates or consider this feature is still important, please reopen it or submit a new request with the most current information.
