### ISSUE TITLE
Jfrog Plugins not reloading with the Reload Rest Api command

### ISSUE THREAD

**Issue by chimajdev** [jfrog/artifactory-user-plugins#302]
How do you send a REST API command? I have gone through the [Reload Plugin Api](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ReloadPlugins) and when I execute my reload command: curl -i -admin:password -X POST http://<local-host>/artifactory/api/plugins/reload

I keep getting this response:

HTTP/1.1 401 Unauthorized
Date: Fri, 15 Nov 2019 17:06:44 GMT
Server: Artifactory/6.0.3
X-Artifactory-Id: 36100672ff68ca0d:6efc78d3:16e5aac9603:-8000
WWW-Authenticate: Basic realm="Artifactory Realm"
Content-Type: application/json
Connection: close
Transfer-Encoding: chunked

{
  "errors" : [ {
    "status" : 401,
    "message" : "Unauthorized"
  } ]

I have the .groovy, .json and .properties files in /etc/plugins

I need some help please!

**Comment by chimajdev** [comment]
I got it to work with curl -v -i -u admin:password -X POST Http://localhost/artifactory/api/plugins/reload

hopefully it works for others having the same problem

**Comment by DarthFennec** [comment]
Glad you were able to solve this yourself! Indeed, you need to be authenticated as an admin user to use the reload API, otherwise you'll get a `401 Unauthorized` response.
