### ISSUE TITLE
Is the plugin cleanDockerImages stil working in version 6.13.x ?

### ISSUE THREAD

**Issue by kad-meedel** [jfrog/artifactory-user-plugins#303]
I have implemented the cleanDockerImages plugin for cleaning docker images, but I can't get any results.

The only thin I get back is:

{
    "status": "okay",
    "dryRun": false,
    "deleted": [

    ]

And I have docker images that meet the clean values I have set.

com.jfrog.artifactory.retention.maxCount: "10"
com.jfrog.artifactory.retention.maxDays: "60"

**Comment by DarthFennec** [comment]
Works for me. Is the repository the images are in listed correctly in the properties file?

**Comment by jfrog-aparicio** [comment]
Closed as unable to reproduce
