### ISSUE TITLE
Artifactory user plugin execution

### ISSUE THREAD

**Issue by jagadeeswar725863** [jfrog/artifactory-user-plugins#309]
Hi Team,

We see the archivalArtifacts plugin loaded in the Artifactory but the execution is not happening. When wetried the execution via REST API it worked. 

Will the plugin not execute by itself, is it mandatory to call via REST API for the execution to happen?

Thanks!

**Comment by DarthFennec** [comment]
You are correct, ArchiveOldArtifacts only runs when you call it via the REST API. You can always create a cron job or something that runs it at regular intervals, if you need.
