### ISSUE TITLE
Dryrun is not working in  Artifactory Pro Power Pack 3.2.1 

### ISSUE THREAD

**Issue by dhrub-git** [jfrog/artifactory-user-plugins#310]
I have tried using the plugin in Artifactory Pro Power Pack 3.2.1 in dryRun=true mode, but it seems it actually deleted the files on that mode. Also, timeUnit and timeInterval is not working properly on this plugin in v3.2.1. Can you please confirm if the issue is with the vresion ? If yes, then how we can use this with v3.2.1.

**Comment by dhrub-git** [comment]
Sorry, forgot to mention I am referring about "Artifactory Artifact Cleanup User Plugin".

**Comment by jfrog-aparicio** [comment]
3.2.1 has been EOL for a very long time. We do not test against it so changes to support newer releases may have broken it or that feature may not have been supported in 3.2.1. In any case, closing this as we will not patch it for 3.x, though you may try an older committed version that may work for you.
