### ISSUE TITLE
cleanDockerImages plugin should allow for ignoring cleanup on specific tags

### ISSUE THREAD

**Issue by shubb30** [jfrog/artifactory-user-plugins#311]
The cleanDockerImages plugin works really well.  

The only problem I have with it is that in some of my docker images, I include the `latest` tag in addition to a build-specific tag.   

When I push a new image with the `latest` tag, Artifactory overwrites the previous tag with the new version of the image, but the Created date stays the same.  So when I run the `cleanDockerImages` plugin, it shows the `latest` tag in the list of artifacts to delete, which is not what I want.

What I propose is in addition to the `maxCount` and `maxDays` labels, there is a third label like `keepTags`, which would be a comma separated list of image tags that will never be deleted, regardless of the other two settings.

I tried taking a stab at writing this, but I am not sure how to get the docker image tag from the `item` object in the `simpleTraverse` function.

**Comment by karanmagdani1** [comment]
I faced a similar issue, I updated the file [here](https://github.com/jfrog/artifactory-user-plugins/blob/master/cleanup/cleanDockerImages/cleanDockerImages.groovy#L88) to add a check 

- if `parentRepoPath` [does not] contain substring `latest` then add it to oldSet

**Comment by agarwva2** [comment]
+1

**Comment by weakcamel** [comment]
if "latest" tag in active use, implementation of https://github.com/jfrog/artifactory-user-plugins/issues/333 would IMO mitigate this problem.

**Comment by harendrar8095** [comment]
Thanks for bringing this up!

As you can see in [our documentation](https://jfrog.com/help/r/jfrog-platform-administration-documentation/package-types-coverage), we are working on a newer, recommended way to extend the JFrog Platform (including Artifactory) in a cloud-native way, called JFrog Workers. Unfortunately, this means that our focus and resources are directed toward that initiative, and we are not able to review and approve new PR or feature request at this time.


We’re closing this for now, but feel free to reopen it if you have any further queries!
