### ISSUE TITLE
Passing exclusion property values in archiveOldartifacts user plugin

### ISSUE THREAD

**Issue by dsakilesh** [jfrog/artifactory-user-plugins#312]
Hi Team,

We have the below requirement.

We have **branches** repos with property key 'branch' with values '<branchname>'
We have **master** repos with property key 'branch' with values 'master' and "type=protected"
We have **tags** repos with property key 'branch' with values '1.1' and "type=protected"

So we need to exclude the archival for tags artifacts and archive only master branch artifacts alone. So could you please provide me the format for the above requirement.
Note : tags artifacts property key 'branch' artifacts have values like 1.1 , 1.2, 1.3 etc

Please provide the Curl command for exclusion

curl -X POST -vvv  -u username:password "https://xyz.com/artifactory/api/plugins/execute/archive_old_artifacts?params=srcRepo=SourceXYZ;ageDays=1;archiveRepo=XYZ-archive;excludePropertySet=branch=master,type=protected"

 as well as the value to be set in the groovy file

 **"def excludePropertySet = params['excludePropertySet'] ? params['excludePropertySet'][0] as String : "**

Thanks in advance!

Regards,
Akilesh D S

**Comment by dsakilesh** [comment]
I have tried below line in groovy file but it deletes all the repos in the srcRepo.
def excludePropertySet = params['excludePropertySet'] ? params['excludePropertySet'][0] as String : 'type[:protected[;branch[:master]]]'

and through the command line we tried below lines, this also deletes all the repos in sourceRepo.

"https://xyz.com/artifactory/api/plugins/execute/archive_old_artifacts?params=srcRepo=SourceXYZ;ageDays=1;archiveRepo=XYZ-archive;excludePropertySet=branch=master,type=protected"

...........;excludePropertySet=branch=master;type=protected"

...........;excludePropertySet=branch:master;type=protected"

etc

But it deletes all the artifacts in the srcRepo.

Could you please provide a proper format for the deletion of master branches?

Thanks in advance

**Comment by agrasth** [comment]
Hi, we can use `excludePropertySet=branch=[*.*, master];type=protected` format to exclude branches with any value containing a dot (e.g., 1.1, 1.2) and include the master branch.
For better understanding you can refer [this](https://github.com/jfrog/artifactory-user-plugins/blob/master/deprecated-plugins/archive/archiveOldArtifacts/README.md).

If you want to pass feature branch as a value for a property, you can replace `/` with `%2F`. For example `feature%2F1234`

**Note**: archiveOldartifacts  plugin is deprecated and incompatible with the most recent Artifactory versions. Please refer to the deprecation notice [here](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations).
