### ISSUE TITLE
cleanDockerImages: dryRun=false is not honored

### ISSUE THREAD

**Issue by e-gris** [jfrog/artifactory-user-plugins#317]
`curl --silent --show-error --request POST  'http://<url>/artifactory/api/plugins/execute/cleanDockerImages?params=dryRun=false'
`

Returns the following JSON

```
{
    "status": "okay",
    "dryRun": true,
    "deleted": [
        
    ]
}
```

**Comment by Akash-Jain-GMI** [comment]
It seems the groovy syntax is not honoring the above configuration for `dryRun` in [cleanDockerImages.groovy](https://github.com/jfrog/artifactory-user-plugins/blob/master/cleanup/cleanDockerImages/cleanDockerImages.groovy) file.

Can you check by changing the below line from 
```groovy
 def dryRun = params['dryRun'] ? params['dryRun'][0] as boolean : false
````
to
```groovy
 def dryRun = params['dryRun'] ? params['dryRun'][0].toBoolean() : false
```

The above change works for me.
You can find the above line [here](https://github.com/jfrog/artifactory-user-plugins/blob/31d2423efb8e660ed3773b7f6ef6293a3b170803/cleanup/cleanDockerImages/cleanDockerImages.groovy#L31).

**Comment by shashank-jfrog** [comment]
Hello,

Thank you for reaching out to us!

Plugins are designed to be highly flexible, allowing you to customize them to meet your specific needs. You can incorporate the suggested changes to align with your requirements.

If you continue to encounter issues with this plugin, we recommend transitioning to our new product feature specifically designed to handle cleanup tasks more effectively. This feature is now generally available (GA) and offers enhanced capabilities for artifact maintenance and management.

For more details and guidance, please refer to our [Cleanup Policies documentation](https://jfrog.com/help/r/jfrog-platform-administration-documentation/package-types-coverage).

We’ll close this ticket for now, but if you have any further questions or need additional assistance, don’t hesitate to reopen it.

Thanks
