### ISSUE TITLE
beforeDownloadRequest error in expireFilesMetadata

### ISSUE THREAD

**Issue by russ-c** [jfrog/artifactory-user-plugins#321]
In Artifactory 7.3.2, Helm chart version 2.2.2, I'm receiving a 500 result code and the following error message whenever I try to download an artifact:

"Could not process download request: Script execution error while trying to execute plugin execution point 'beforeDownloadRequest' (expireFilesMetadata.groovy:65)"

I've confirmed I'm using the latest plugin code.

Can you please help?

Russell

**Comment by DarthFennec** [comment]
Have you checked the Artifactory logs? There should be a stacktrace with more information. Thanks!

**Comment by russ-c** [comment]
Thanks for getting back - upon further debugging I found that it was using old code in a persistent volume.
