### ISSUE TITLE
What are the values of the Post JSON Body?

### ISSUE THREAD

**Issue by msharaf** [jfrog/artifactory-user-plugins#327]
When I configure this plugin, to post to Mattermost, it provides the user name, path and repository.  I assume this is part of json body, and would like to know the name of the keys that are associated, so I can parse the json body.

**Comment by jfrog-aparicio** [comment]
I assume you are talking about the webhook plugin and are using the Slack format. You can see what is done in the [source code](https://github.com/jfrog/artifactory-user-plugins/blob/master/webhook/webhook.groovy#L408) for that format.
