### ISSUE TITLE
JFrog CLA link is dead

### ISSUE THREAD

**Issue by NetAppBlueDevil** [jfrog/artifactory-user-plugins#328]
The Contributing.md states

"Click here to submit the JFrog CLA. This should only take a minute to complete and is a one-time process." with the link going to  https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N

Clicking the link states the form is no longer active.  How is the process now to be able to contribute to this project/repository?

**Comment by DarthFennec** [comment]
Yeah, we've started using something different, and we still need to change the contributing file to reflect that.

Now, when you create a pull request, you'll get a comment from CLAassistant with the correct link. After you sign, the comment should update to say you've signed. Let me know if you have any issues with this.

**Comment by NetAppBlueDevil** [comment]
I have a need to have an internal opensource team review any contribution licenses before being allowed to submit code, so being able to see the license terms prior to a PR is something I need.

**Comment by DarthFennec** [comment]
I see. Try https://cla-assistant.io/jfrog/artifactory-user-plugins?pullRequest=328

**Comment by NetAppBlueDevil** [comment]
Thanks, I was able to pull a copy for my internal approval.

Daniel
