### ISSUE TITLE
Is it possible that concurrently multiple  events, trigger only one summarized webhook

### ISSUE THREAD

**Issue by saggl** [jfrog/artifactory-user-plugins#330]
it is possible to send only one webhook instead of several if you set several properties at the same time like:
``
jfrog rt sp Repo / test.txt "a=1; b=2; c=3"
``

My intention is that if I get several individual webhooks on the jenkins, I cannot process all payloads in one build.

so I can't filter on:
``
if a=1 and b=2 and c=3 do that
``
or
``
if a=6 and b=7 and c=8 do this
``

**Comment by jfrog-aparicio** [comment]
At the moment this is not possible with the current implementation. If you have very specific requirements, such as alert me if properties x, y and z are set to values a, b, c or something like that, the best option would likely be to create a custom plugin that checks for these conditions when an action is performed on an item.

Will close for now as this is not something that webhook plugin can currently do nor (realistically) be enhanced to handle.
