### ISSUE TITLE
Can not use securityReplication plugin on Version 7

### ISSUE THREAD

**Issue by lyqwaterway** [jfrog/artifactory-user-plugins#343]
After v7, we have not DR feature.

We want to use securityReplication plugin to replicate users , groups and permissions

But we encountered an error when we install the plugin as below:
https://github.com/jfrog/artifactory-user-plugins/blob/master/security/securityReplication/securityReplication.groovy

/opt/jfrog/artifactory/var/etc/artifactory/plugins/securityReplication.groovy: 30: unable to resolve class org.artifactory.common.ArtifactoryHome
 @ line 30, column 1.
   import org.artifactory.common.ArtifactoryHome

**Comment by jfrog-aparicio** [comment]
This plugin was never tested for Artifactory 7. It has been deprecated for a while now so we will not be making changes to it.

**Comment by lyqwaterway** [comment]
@jfrog-aparicio Do we have any solution to replicate security info to another cluster
Could we export users groups permission and import to other instance
access.config.latest.xml?

**Comment by jfrog-aparicio** [comment]
If you are a customer with support, I would contact them and they can suggest other solutions. The official solution is to use [JFrog Access Federation ](https://www.jfrog.com/confluence/display/JFROG/Access+Federation), depending on the subscription you have, that may be the best option. I believe you can do an access import and that should cover some use cases but not other like keeping different instance in sync realtime.
