### ISSUE TITLE
ArtifactCleanupPlugin: cron not triggered with multiple policies

### ISSUE THREAD

**Issue by brikendr** [jfrog/artifactory-user-plugins#344]
Hi,

I am using the artifact cleanup user plugin on our artifactory instance to artifacts from various repositories (generic, conan, python etc). I had to create two different policies where the first one is to delete artifacts older than one month and the second one is to delete artifacts older than a week. Here is an example of my json file:

```
{
  "policies": [
    {
      "cron": "0 1 0 * * ?",
      "repos": [
        "repository_A",
        "repository_B"
      ],
      "timeUnit": "month",
      "timeInterval": 1,
      "dryRun": false,
      "paceTimeMS": 500,
      "disablePropertiesSupport": true
    },
    {
      "cron": "0 2 0 * * ?",
      "repos": [
        "repository_C"
      ],
      "timeUnit": "day",
      "timeInterval": 7,
      "dryRun": false,
      "paceTimeMS": 500,
      "disablePropertiesSupport": true
    }
  ]
}
```

As you can see i have configured in a way that the first cron is executed at 01:00 AM every night and the second one at 02:00AM respectively. 

Here is a snippet of the artifactory log after the update was completed and plugins were reloaded:

```
artifactory_ssd2 | 2020-12-02 08:05:07,576 [pool-150-thread-1] [INFO ] (o.j.c.ConfigWrapperImpl:342) - [Node ID: 573d0b92cf0a]  detected local  modify for config 'artifactory/config/plugins/artifactCleanup.groovy'
artifactory_ssd2 | 2020-12-02 08:06:59,747 [http-nio-8081-exec-1547] [INFO ] (o.a.a.p.GroovyRunnerImpl:249) - Script 'artifactCleanup.groovy' has changed. Reloading all scripts
artifactory_ssd2 | 2020-12-02 08:06:59,830 [http-nio-8081-exec-1547] [INFO ] (o.a.a.p.GroovyRunnerImpl:301) - Loading script from 'artifactCleanup.groovy'.
artifactory_ssd2 | 2020-12-02 08:07:00,094 [http-nio-8081-exec-1547] [INFO ] (artifactCleanup     :-2) - Schedule job policy list: [[cron:0 1 0 * * ?, disablePropertiesSupport:true, dryRun:false, paceTimeMS:500, repos:[repository_A, repository_B], timeInterval:1, timeUnit:month], [cron:0 2 0 * * ?, disablePropertiesSupport:true, dryRun:false, paceTimeMS:500, repos:[repository_C], timeInterval:7, timeUnit:day]]
artifactory_ssd2 | 2020-12-02 08:07:00,109 [http-nio-8081-exec-1547] [INFO ] (o.a.a.p.GroovyRunnerImpl:345) - Script 'artifactCleanup' loaded.
```

After waiting a day, i see that the last written log from the `artifactCleanup` plugin is the one above. So there was basically no cron trigger scheduled at all.

Groovy script has been updated to latest master from 03.12.2020. Any help would be appreciated. Thanks

**Comment by cschyma** [comment]
I confirm having the same problem with the latest Groovy script as of now and Artifactory 7.9.0.

**Comment by cschyma** [comment]
Please vote for this bug to be fixed at https://www.jfrog.com/jira/browse/RTFACT-24307 as JFrog is prioritizing by community feedback. Right now there isn't even a ETA set for solving this bug.

**Comment by vesubramanian** [comment]
Where is this policy defined? It's not mentioned anywhere in the documentation? How can we set this plugin to run automatically based on a schedule?

**Comment by martinm82** [comment]
@brikendr are you using an HA cluster? I had a similar problem and after enabling full logging (debug) on Artifactory I realised that I forgot to set the `primary` flag to true in `system.yaml`.

**Comment by brikendr** [comment]
@martinm82 no we are not using HA cluster at the moment.

**Comment by quinh** [comment]
I've the same issue, but my config only has one policy and not even with one it's being triggered.

**Comment by harendrar8095** [comment]
Thanks for bringing this up!

If you’re encountering issues with the cleanup plugin, we recommend moving to our new product feature designed to handle cleanup tasks more effectively. This feature has reached General Availability (GA) and offers enhanced capabilities for maintaining and managing artifacts.

You can find more information and guidance on using this new feature in our [GA documentation](https://jfrog.com/help/r/jfrog-platform-administration-documentation/package-types-coverage).

We’re closing this ticket since it’s an older one, but please feel free to reopen it if you have further questions!
