### ISSUE TITLE
repoQuota Plugin is not warning users

### ISSUE THREAD

**Issue by lsauer** [jfrog/artifactory-user-plugins#345]
The repoQuota Plugin appeares as a failed upload rather than providing users with a meaningful error message. Ideally the responses should be configurable or kept generic for the various protocols.

If users don't know their repo has exceeded the Quota, then they will think something else is broken.

**Comment by nehamjfrog** [comment]
Thank you for submitting your feature request. We appreciate all user feedback. However, as this request has been dormant for some time and several plugins have been deprecated in the latest releases, we are closing it for now. If you have any modifications or consider this feature is still essential please reopen it or create a new request with the most recent data.
