### ISSUE TITLE
Questions on Plugin Usage

### ISSUE THREAD

**Issue by vesubramanian** [jfrog/artifactory-user-plugins#391]
I have some questions on this plugin usage.
1. How to install this plugin? Do we need to manually copy the files to the server? How can we do such things in SAAS solution of Artifactory where there will be no server access?
2.  Will this plugin run automatically on a schedule? If yes, how and where to define that?
3.  Can we specify the properties along with JFrog CLI commands instead of directly adding them in the Dockerfile? I use GitHub Action as my CI tool where I use JFrog CLI to push Docker Images to Artifactory.

**Comment by spuder** [comment]
Did you figure this out? 

https://www.jfrog.com/confluence/display/JFROG/User+Plugins#UserPlugins-DeployingPlugins

>Deploying Plugins
Place your plugin files under $JFROG_HOME/artifactory/var/etc/artifactory/plugins.

>Artifactory HA Plugins Directory

>If you are working with a High Availability cluster your user plugins should be added to the primary node and they will be propagated to the entire cluster.

>Any file name ending with .groovy is loaded on startup. You can have multiple plugin files which are loaded in alphabetical order. Callbacks defined in plugins are called by the order they were loaded.

**Comment by shashank-jfrog** [comment]
Hi,
It seems like you already have the answer to your questions. If you have any new questions or suggestions, or if you’re not satisfied with the answers, please feel free to open a new issue.

Thanks!
