### ISSUE TITLE
Artifactory migration user plugin fails with No signature of method: com.sun.proxy.$Proxy195.localRepoDescriptorByKey() is applicable for argument types: (java.lang.String

### ISSUE THREAD

**Issue by martinm82** [jfrog/artifactory-user-plugins#392]
I was trying out the migration helper user plugin (https://github.com/jfrog/artifactory-user-plugins/tree/master/migration/artifactoryMigrationHelper) on our Artifactory instance and hit the following problem while executing the user plugin:

```
Failed to setup Artifactory migration: No signature of method: com.sun.proxy.$Proxy195.localRepoDescriptorByKey() is applicable for argument types: (java.lang.String) values: [artifactory-build-info]\nPossible solutions: virtualRepoDescriptorByKey(java.lang.String
```

We are using Artifactory 7.19.8.

It seems that the plugin does not support the builtin repository `artifactory-build-info`. One way to fix this was to exclude the build-info repo:

```
    log.debug "Existing local repositories: $existingRepositories"
    def missingRepositories = localConfig.localRepositories.localRepository.findAll {
        !(it.key in existingRepositories && it.key != "artifactory-build-info")
    }
```

EDIT: 
The problem is that the plugin uses two ways of accessing repositories. The ones from remote are fetched via the REST API which does not return the internal artifactory-build-info repository. While obtaining local repositories on source Artifactory is done via some internal APIs which on the other side return the artifactory-build-info.

**Comment by martinm82** [comment]
Same problem happens with repositories that do not exist yet on target. Seems that the remote creation of the repos in this plugin is broken.

**Comment by sureshvenkatesan** [comment]
There is a PR #403 for this

**Comment by agrasth** [comment]
The artifactoryMigrationHelper plugin is deprecated and incompatible with the most recent Artifactory versions. Please refer to the deprecation notice [here](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations)
