### ISSUE TITLE
Could we view the artifacts to be cleaned up in dry_run mode?

### ISSUE THREAD

**Issue by tianqiliu-RBLX** [jfrog/artifactory-user-plugins#401]
We wanna check how many artifacts would be deleted in the dry_run mode but looks like the POST request is returning nothing? Is there any easy way we could check?

**Comment by shashank-jfrog** [comment]
Hi,
The number of artifacts that are to be deleted is present in the logs of the artifactCleanup plugin. These logs would be available as a part of artifactory application logs. For enabling these logs, please refer - https://jfrog.com/help/r/how-can-i-write-a-user-plugin-log-to-a-different-log-file/subject.

If you have any new questions or suggestions, or if you’re not satisfied with the answer, please feel free to open a new issue.

Thanks
