### ISSUE TITLE
mavenSnapshotCleanupWhenRelease: Update Maven Metadata?

### ISSUE THREAD

**Issue by TobiX** [jfrog/artifactory-user-plugins#407]
The plugin `mavenSnapshotCleanupWhenRelease` removes Maven artifacts from a repository, but leaves `maven-metadata.xml` unmodified, which now lists an unavailable version. This can lead to errors in some corner cases. I think it would be a good idea if the plugin recalculated the maven metadata after removal of the artifact.

**Comment by harendrar8095** [comment]
Thanks @TobiX for bringing this up!,
If you’re still encountering issues with the artifact cleanup, we recommend moving to our new product feature designed to handle cleanup tasks more effectively. This feature has reached General Availability (GA) and offers enhanced capabilities for maintaining and managing artifacts.

You can find more information and guidance on using this new feature in our [Cleanup policies](https://jfrog.com/help/r/jfrog-platform-administration-documentation/package-types-coverage).

We’ll close this for now, but if you have any further questions, feel free to reopen it!
