### ISSUE TITLE
synchronizeLdapGroups: unable to login when token username  has '@01f'

### ISSUE THREAD

**Issue by ib-ak** [jfrog/artifactory-user-plugins#408]
synchronizeLdapGroups: unable to login when token username  has '@01f'

`token:jfmc@01f.......................`

**Comment by agrasth** [comment]
This synchronizeLdapGroups plugin is deprecated and incompatible with the most recent Artifactory versions. Please view the deprecation notice [here](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations).
