### ISSUE TITLE
artifactCleanup - Questions about operating.

### ISSUE THREAD

**Issue by malceore** [jfrog/artifactory-user-plugins#411]
This plugin specifically.
https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup/artifactCleanup

1. Does this plugin work on Artifactory 7.31?
2. Does this plugin log what files it removes anywhere, even on a dry-run?

**Comment by azranchen** [comment]
yes
To ensure logging for this plugin, edit ${ARTIFACTORY_HOME}/etc/logback.xml to add:

    <logger name="artifactCleanup">
        <level value="info"/>
    </logger>

then look at jforg/artifactory/var/log/artifactory-service.log

**Comment by dmckernanacv** [comment]
Do these plugins work with the OSS version? How can I modify the log for the helm chart?

**Comment by agrasth** [comment]
Yes, this plugin works on Artifactory 7.31. It logs deletions to artifactory-service.log, even in dry-run mode, when configured. 

To set up logging in the OSS version with Helm, add a custom logback.xml with:

```
<logger name="artifactCleanup">
    <level value="info"/>
</logger>
```
Then, mount this updated logback.xml through Helm’s extraConfigMaps or extraVolumes.
