### ISSUE TITLE
How to use buildCleanup Plugin? path: artifactory-user-plugins/cleanup/buildCleanup/

### ISSUE THREAD

**Issue by alenwong56** [jfrog/artifactory-user-plugins#413]
Hello, master. Now I need to use the plug-in to let jfrog help me delete the build package to 150 days ago. do I just need to add < buildclean uptest. groovy > upload to the following path: 
$jfrog_ HOME/artifactory/var/etc/artifactory/plugins
Can I use it? 
@[abhinavkhanna-sf](https://github.com/abhinavkhanna-sf)
------------------------
and ..
But after I upload, the curl request appears 404
![image](https://user-images.githubusercontent.com/76940967/164006500-265b5df2-48c7-4966-b46d-f00e7668b41e.png)
![image](https://user-images.githubusercontent.com/76940967/164006942-d14b9666-cefc-421a-a3fd-07a9b5c1fbba.png)

**Comment by agrasth** [comment]
Yes, you can use a Groovy plugin in JFrog Artifactory to delete build packages older than 150 days. 

To address a 404 error when attempting to reload the plugin, please check the Artifactory URL and ensure that the URL used in your curl command matches your Artifactory server’s address. Based on your example, it should be

`curl -u admin:19920506Aa! -X POST "http://192.168.150.128:8081/artifactory/api/plugins/reload"`

Note: /artifactory is typically part of the path. Without this, the request may result in a 404 error.

Also ensure that the user (admin in this case) has adequate permissions to reload plugins.
