### ISSUE TITLE
Artifact cleanup plugin exection 

### ISSUE THREAD

**Issue by gyanendra0501** [jfrog/artifactory-user-plugins#416]
Hi Team, 
To execute cleanup plugin do we need pro version , and to cleanup artifacts someone already written script ?

**Comment by agrasth** [comment]
Hi, you don't need a pro version, to execute cleanup plugin you can refer [this](https://github.com/jfrog/artifactory-user-plugins/blob/master/cleanup/artifactCleanup/artifactCleanup.groovy) existing plugin.
You can also use cleanup policies, [product feature](https://jfrog.com/help/r/jfrog-platform-administration-documentation/package-types-coverage).
