### ISSUE TITLE
Artifactory replication based on filterReplicationByProperty

### ISSUE THREAD

**Issue by divlaks** [jfrog/artifactory-user-plugins#420]
Hi,

We have a use case, where we set two replications for a repo, of which one should replicate all artifacts and the other should replicate based on the property. Is there any way to achieve this using filterReplicationByProperty plugin.

Regards,
Dhivya

**Comment by agrasth** [comment]
Hi, filterReplicationByProperty plugin filters items for replication by their properties, only items having at least one of a specified set of properties will be replicated.

But now filterReplicationByProperty plugin is deprecated and incompatible with the most recent Artifactory versions. Please refer to the deprecation notice [here](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations).
