### ISSUE TITLE
unable to resolve class org.artifactory.storage.db.binstore.dao.BinariesDao in Arfactory 7.49.5

### ISSUE THREAD

**Issue by davidshinjfrog** [jfrog/artifactory-user-plugins#429]
Error loading script from '/opt/jfrog/artifactory/var/etc/artifactory/plugins/filestoreIntegrity.groovy'.
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/opt/jfrog/artifactory/var/etc/artifactory/plugins/filestoreIntegrity.groovy: 2: unable to resolve class org.artifactory.storage.db.binstore.dao.BinariesDao
 @ line 2, column 1.
   import org.artifactory.storage.db.binstore.dao.BinariesDao

---------------
The recent Artifactory has changed the classpath. e.g. v.7.49.5

As a workaround,  we should use the new path as following
import org.jfrog.storage.binstore.db.dao.BinariesDao

**Comment by nehamjfrog** [comment]
This filestoreintegrity plugin is deprecated and incompatible with the most recent Artifactory versions. Please refer to the deprecation notice [here](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations)
