### ISSUE TITLE
Deprecation of LayoutProperties

### ISSUE THREAD

**Issue by markgalpin** [jfrog/artifactory-user-plugins#447]
@shrajfr12 I saw you deprecated LayoutProperties.   Was planning to use that as example code on how to potentially extract GAVC data from a layout.   Do we know what its errors were?  Given the ability to test it I'd be happy to get it running again.

**Comment by harendrar8095** [comment]
Thanks for the question!

With `LayoutProperties` deprecated as a plugin, we’ve introduced it as a [product feature](https://jfrog.com/help/r/jfrog-artifactory-documentation/configure-repository-layouts) that may align well with what you’re looking to accomplish. Could you give the new [LayoutProperties](https://jfrog.com/help/r/jfrog-artifactory-documentation/configure-repository-layouts) feature a try and see if it fulfils your requirements for extracting GAVC data?

We’ll close this question for now, but please feel free to reopen it or start a new thread if you have further insights or feedback to share!
