### ISSUE TITLE
Storage User Plugins - before & after delete capture artifactes size details  

### ISSUE THREAD

**Issue by sbhaskarareddy** [jfrog/artifactory-user-plugins#449]
Hi Team,

Is there any way to get the Get the artifacts size details  before and after delete of the repos ? we need groovy code details and also this has to update in log file as well .

storage { 
 
 beforeDelete { item -> 
 } 
 
 /** 
 * Handle after delete events. 
 * 
 * Closure parameters: 
 * item (org.artifactory.fs.ItemInfo) - the original item deleted. 
 */ 
 afterDelete { item -> 
 } 
 
Kindly any help on this please ?

**Comment by harendrar8095** [comment]
Thanks for reaching out.

To get artifact size details before and after deletion, you can refer to the [Artifactory Public API documentation](https://releases.jfrog.io/artifactory/oss-releases-local/org/artifactory/artifactory-papi/%5BRELEASE%5D/artifactory-papi-%5BRELEASE%5D-javadoc.jar!/org/artifactory/resource/RepoResourceInfo.html#getSize()) for APIs that fetch size details.

As you can see in our documentation, we’re working on a newer, recommended way to extend the JFrog Platform (including Artifactory) in a cloud-native way, called [JFrog Workers](https://jfrog.com/platform/workers/). We suggest trying out [JFrog Workers](https://jfrog.com/platform/workers/) to handle this use case.

We'll close this question for now, but feel free to reopen it if you have further insights or questions!
