### ISSUE TITLE
filestoreIntegrity plugin fails with error against 7.49.8

### ISSUE THREAD

**Issue by lawdt** [jfrog/artifactory-user-plugins#452]
after fixing classpath to org.jfrog.storage.binstore.db.dao.BinariesDao like in #431 i recieve error 500:
```
{
  "errors" : [ {
    "status" : 500,
    "message" : "No signature of method: org.jfrog.storage.binstore.db.dao.BinariesDao.exists() is applicable for argument types: (String) values: [5401e04b22c0fdf279e6b2b14b9dcb46df371415]\nPossible solutions: exists(java.lang.String, java.lang.String), wait(), equals(java.lang.Object), wait(long), is(java.lang.Object), print(java.lang.Object)"
  } ]
```

**Comment by nehamjfrog** [comment]
This filestoreintegrity plugin is deprecated and incompatible with the most recent Artifactory versions. Please refer to the deprecation notice [here](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations)
