### ISSUE TITLE
cleanDockerImages to clean up multi arch images

### ISSUE THREAD

**Issue by shivako** [jfrog/artifactory-user-plugins#456]
Currently, the plugin - cleanDockerImages (https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup/cleanDockerImages) looks at only manifest.json to find the container images. But multi-arch images do have list.manifest.json and not manifest.json.  Can you help to fix it? Or I can make those changes. Link to submit CLA is not working. Appreciate any guidance and help.

Thanks
Shiva

**Comment by smartin-qb** [comment]
FYI - https://jfrog.atlassian.net/browse/RTFACT-30432

**Comment by shashank-jfrog** [comment]
Hi,

Thanks for the suggestion! We recommend using the [Cleanup Policies](https://jfrog.com/help/r/jfrog-platform-administration-documentation/package-types-coverage) feature for any artifact cleanup needs.
