### ISSUE TITLE
Remote Backup User Plugin "remoteBackup.groovy" did not work for the docker repo

### ISSUE THREAD

**Issue by gyzong1** [jfrog/artifactory-user-plugins#462]
Remote Backup User Plugin "remoteBackup.groovy" did not work for the docker repo, only manifest.json has been copied, and the image layers were not copied.

Reproduction steps:
1. Create two docker repositories "docker-local" and "docker-local-copy"
2. Deploy user plugin "remoteBackup.groovy" and configuration file "remoteBackup.json"
3. Push docker image to docker-local via "docker push localhost:8082/docker-local/busybox:v1"
4. Check "docker-local-copy", only the manifest.json has been copied
![docker-local-copy](https://github.com/jfrog/artifactory-user-plugins/assets/40457486/4c1db141-8695-46e4-bdc9-f37747a1ab34)

Request support for docker-type repositories.

**Comment by nehamjfrog** [comment]
I performed the procedures outlined above, and the plugin appears to be operating well. I am currently closing the issue; please retry and revisit the issue if it persists.
