### ISSUE TITLE
Missing parameters for deleteEmptyDirs script

### ISSUE THREAD

**Issue by bienstock** [jfrog/artifactory-user-plugins#65]
Need to add `-H "Content-Length: 0"` to the curl command like so:

`curl -X POST -v -u admin:password "http://localhost:8080/artifactory/api/plugins/execute/deleteEmptyDirsPlugin?params=paths=repo,otherRepo/some/path"  -H "Content-Length: 0"`

Otherwise, you get the following error:

```
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

**Comment by DarthFennec** [comment]
I can't seem to reproduce this. What versions of Artifactory and curl are you using? Also, do you have some kind of proxy between curl and Artifactory? I know that some frameworks and programs incorrectly send 411 in response to a POST without a body, but no version of Artifactory I know of does this.

**Comment by bienstock** [comment]
Artifactory Version 4.7.5 (Pro version)
curl  - 7.35.0-1ubuntu2.8

**Comment by DarthFennec** [comment]
I'm still unable to reproduce this behavior. There might be something else on your network or server that is causing this to happen.

**Comment by meedel** [comment]
What do I have to implement in the logback.xml to see the messages in the logging?

<logger name="?????????????">
        <level value="info"/>
    </logger

**Comment by DarthFennec** [comment]
Hi @meedel, it should be:

```xml
<logger name="deleteEmptyDirs">
    <level value="info"/>
</logger>
```

The name to use is the name of the groovy file, without the `.groovy` extension.

**Comment by edwardl50** [comment]
Hi,
Add this to the end of logback.xml before the /configuration to see all the
logs printed out by the plugin.

Regards,
Ed

<logger name="cleanup/deleteEmptyDirs">
    <level value="debug"/>
</logger>

**Comment by edwardl50** [comment]
oops just the plugin name.
disregard.

<logger name="deleteEmptyDirs">
    <level value="debug"/>
</logger>
