### ISSUE TITLE
integration of Artifactory with Bintray

### ISSUE THREAD

**Issue by perfecto25** [jfrog/artifactory-user-plugins#68]
in Artif v 4.12.2, configuring Distribution page, on the Rules page, if I create a new Generic rule and save the page, and then go back to look at it, the rule disappears. Generic rules do not get saved for some reason.  

![pic1](https://cloud.githubusercontent.com/assets/10224886/18788037/4b2013b8-8173-11e6-8f77-92b57609ab90.png)
![pic2](https://cloud.githubusercontent.com/assets/10224886/18788038/4ed4d2b4-8173-11e6-87cb-aa2439ef2819.png)

**Comment by DarthFennec** [comment]
That's strange. I can't seem to reproduce this, generic rules save fine for me ... does anything weird show up in your artifactory.log file?

Just for future reference, this may not be the most optimal place to ask questions like this. This place is more for questions or bug reports regarding user plugins.
