### ISSUE TITLE
Issue/Clarification Staging Plugin

### ISSUE THREAD

**Issue by nandhusriram** [jfrog/artifactory-user-plugins#77]
I am running Artifactory 5.x, Cloudbees jenkins . I am using the staging plugin to do the release staging process. I am running into this weird issue and I am hoping  somebody already ran across similar issue like mine. If I have a job in jenkins root folder  , under All , staging plugin works like a champ , but if have a build job nested  under folders , am getting illegal argument exception and get all builds  call  is empty  and staging fails.

Any help would be appreciated.

**Comment by DarthFennec** [comment]
Hello,

Could you provide example REST calls for a staging that works and one that doesn't? That should help clarify the issue for me.

Thanks for bringing this up!
